import { useEffect, useState } from 'react';
import { supabase } from './supabase';

const tabs = [['dashboard','Dashboard'],['chapters','Chapters'],['upload','Upload Chapter'],['comments','Comments'],['announcements','Announcements'],['media','Media']];
const N='Chapter Number', T='Title', D='Description', C='Cover url';

export default function AdminPanel({ onBack }) {
 const [tab,setTab]=useState('dashboard'),[chapters,setChapters]=useState([]),[comments,setComments]=useState([]),[announcements,setAnnouncements]=useState([]),[media,setMedia]=useState([]),[loading,setLoading]=useState(true),[notice,setNotice]=useState(''),[editing,setEditing]=useState(null),[form,setForm]=useState({number:'',title:'',description:'',cover:''}),[files,setFiles]=useState([]),[uploading,setUploading]=useState(false);
 const load=async()=>{setLoading(true);const [ch,co,an,me]=await Promise.all([supabase.from('chapters').select('*').order(N,{ascending:true}),supabase.from('comments').select('*').order('created_at',{ascending:false}).limit(100),supabase.from('announcements').select('*').limit(100),supabase.from('media').select('*').limit(100)]);if(ch.error)setNotice(`Chapters: ${ch.error.message}`);setChapters(ch.data||[]);setComments(co.data||[]);setAnnouncements(an.data||[]);setMedia(me.data||[]);setLoading(false)};
 useEffect(()=>{load()},[]);
 const saveChapter=async()=>{if(!form.number||!form.title)return setNotice('Chapter number and title are required.');const values={[N]:Number(form.number),[T]:form.title,[D]:form.description,[C]:form.cover||null};const r=editing?await supabase.from('chapters').update(values).eq(N,editing):await supabase.from('chapters').insert([values]);if(r.error)return setNotice(`Error: ${r.error.message}`);setNotice(editing?'Chapter updated.':'Chapter created.');setEditing(null);setForm({number:'',title:'',description:'',cover:''});await load()};
 const deleteChapter=async n=>{if(!confirm(`Delete chapter ${n}? This cannot be undone.`))return;const r=await supabase.from('chapters').delete().eq(N,n);setNotice(r.error?`Error: ${r.error.message}`:'Chapter deleted.');if(!r.error)await load()};
 const uploadChapter=async()=>{if(!form.number||!form.title||!files.length)return setNotice('Number, title and at least one page are required.');setUploading(true);try{const {data:chapter,error}=await supabase.from('chapters').insert([{[N]:Number(form.number),[T]:form.title,[D]:form.description,[C]:form.cover||null}]).select().single();if(error)throw error;for(let i=0;i<files.length;i++){const f=files[i],ext=f.name.split('.').pop()||'jpg',name=`${form.number}/page_${i+1}_${Date.now()}.${ext}`;setNotice(`Uploading page ${i+1} of ${files.length}...`);const u=await supabase.storage.from('chapter-pages').upload(name,f);if(u.error)throw u.error;const {data:url}=supabase.storage.from('chapter-pages').getPublicUrl(name);const p=await supabase.from('chapter_pages').insert([{chapter_id:chapter.id,page_number:i+1,image:url.publicUrl}]);if(p.error)throw p.error}setNotice('Chapter uploaded successfully.');setForm({number:'',title:'',description:'',cover:''});setFiles([]);await load();setTab('chapters')}catch(e){setNotice(`Error: ${e.message}`)}finally{setUploading(false)}};
 const delComment=async id=>{const r=await supabase.from('comments').delete().eq('id',id);setNotice(r.error?`Error: ${r.error.message}`:'Comment deleted.');if(!r.error)await load()};
 const reply=async c=>{const text=prompt('Reply to this comment:');if(!text?.trim())return;const {data}=await supabase.auth.getUser();const r=await supabase.from('comments').insert([{chapter_id:c.chapter_id,user_id:data.user?.id,parent_id:c.id,content:text.trim()}]);setNotice(r.error?`Reply failed: ${r.error.message}`:'Reply posted.');if(!r.error)await load()};
 const Card=({title,value,onClick})=><button onClick={onClick} className="rounded-2xl border border-zinc-200 bg-white p-5 text-left shadow-sm dark:border-zinc-800 dark:bg-zinc-900"><p className="text-sm text-zinc-500">{title}</p><p className="mt-2 text-3xl font-bold">{value}</p></button>;
 return <div className="min-h-screen bg-zinc-50 text-zinc-900 dark:bg-zinc-950 dark:text-white"><header className="sticky top-0 z-20 border-b bg-white/95 px-4 py-4 dark:border-zinc-800 dark:bg-zinc-950/95"><div className="mx-auto flex max-w-7xl items-center justify-between"><div><button onClick={onBack} className="text-sm text-zinc-500">← Back to site</button><h1 className="text-xl font-bold">Atma Rekha Admin</h1></div><button onClick={load} className="rounded-xl border px-4 py-2 text-sm">Refresh</button></div></header><main className="mx-auto max-w-7xl px-4 py-6"><div className="mb-6 flex gap-2 overflow-x-auto">{tabs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`whitespace-nowrap rounded-xl px-4 py-2 text-sm font-medium ${tab===id?'bg-zinc-900 text-white dark:bg-white dark:text-zinc-900':'border bg-white dark:border-zinc-800 dark:bg-zinc-900'}`}>{label}</button>)}</div>{notice&&<div className="mb-5 rounded-xl border bg-white p-4 text-sm dark:border-zinc-800 dark:bg-zinc-900">{notice}</div>}{loading?<div>Loading admin data...</div>:<>
 {tab==='dashboard'&&<div><h2 className="mb-5 text-2xl font-bold">Dashboard</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card title="Chapters" value={chapters.length} onClick={()=>setTab('chapters')}/><Card title="Comments" value={comments.length} onClick={()=>setTab('comments')}/><Card title="Announcements" value={announcements.length} onClick={()=>setTab('announcements')}/><Card title="Media" value={media.length} onClick={()=>setTab('media')}/></div></div>}
 {tab==='chapters'&&<section><div className="mb-5 flex items-center justify-between"><h2 className="text-2xl font-bold">Manage Chapters</h2><button onClick={()=>{setEditing(null);setForm({number:'',title:'',description:'',cover:''});setTab('upload')}} className="rounded-xl bg-zinc-900 px-4 py-2 text-sm font-semibold text-white dark:bg-white dark:text-zinc-900">+ New Chapter</button></div><div className="grid gap-4">{chapters.map(c=><div key={c[N]} className="rounded-2xl border bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><div className="flex items-center justify-between gap-4"><div><p className="text-xs text-zinc-500">Chapter {c[N]}</p><h3 className="text-lg font-bold">{c[T]}</h3><p className="mt-1 text-sm text-zinc-500">{c[D]||'No description'}</p>{c[C]&&<img src={c[C]} alt="Cover" className="mt-3 h-20 w-14 rounded object-cover"/>}</div><div className="flex gap-2"><button onClick={()=>{setEditing(c[N]);setForm({number:c[N],title:c[T]||'',description:c[D]||'',cover:c[C]||''});setTab('upload')}} className="rounded-lg border px-3 py-2 text-sm">Edit</button><button onClick={()=>deleteChapter(c[N])} className="rounded-lg border border-red-200 px-3 py-2 text-sm text-red-600">Delete</button></div></div></div>)}</div></section>}
 {tab==='upload'&&<section className="max-w-2xl"><h2 className="mb-5 text-2xl font-bold">{editing?`Edit Chapter ${editing}`:'Upload Chapter'}</h2><div className="space-y-4 rounded-2xl border bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900"><input type="number" value={form.number} onChange={e=>setForm({...form,number:e.target.value})} placeholder="Chapter number" className="w-full rounded-xl border p-3 dark:border-zinc-700 dark:bg-zinc-950" disabled={!!editing}/><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Chapter title" className="w-full rounded-xl border p-3 dark:border-zinc-700 dark:bg-zinc-950"/><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Description" rows="4" className="w-full rounded-xl border p-3 dark:border-zinc-700 dark:bg-zinc-950"/><input value={form.cover} onChange={e=>setForm({...form,cover:e.target.value})} placeholder="Cover image URL" className="w-full rounded-xl border p-3 dark:border-zinc-700 dark:bg-zinc-950"/>{!editing&&<input type="file" multiple accept="image/*" onChange={e=>setFiles(Array.from(e.target.files||[]))} className="w-full rounded-xl border p-3 dark:border-zinc-700"/>}<button onClick={editing?saveChapter:uploadChapter} disabled={uploading} className="w-full rounded-xl bg-zinc-900 py-3 font-semibold text-white disabled:opacity-50 dark:bg-white dark:text-zinc-900">{uploading?'Uploading...':editing?'Save Changes':'Upload Chapter'}</button></div></section>}
 {tab==='comments'&&<section><h2 className="mb-5 text-2xl font-bold">Comments</h2>{comments.length?<div className="space-y-3">{comments.map(c=><div key={c.id} className="rounded-2xl border bg-white p-4 dark:border-zinc-800 dark:bg-zinc-900"><p className="text-sm">{c.content||c.text||'(empty comment)'}</p><div className="mt-3 flex gap-2"><button onClick={()=>reply(c)} className="rounded-lg border px-3 py-1.5 text-sm">Reply</button><button onClick={()=>delComment(c.id)} className="rounded-lg border border-red-200 px-3 py-1.5 text-sm text-red-600">Delete</button></div></div>)}</div>:<div className="rounded-2xl border bg-white p-6 text-sm text-zinc-500 dark:border-zinc-800 dark:bg-zinc-900">No comments available.</div>}</section>}
 {tab==='announcements'&&<section><h2 className="mb-5 text-2xl font-bold">Announcements</h2><div className="space-y-3">{announcements.map(a=><div key={a.id} className="rounded-2xl border bg-white p-4 dark:border-zinc-800 dark:bg-zinc-900"><h3 className="font-semibold">{a.title||a.Title||'Announcement'}</h3><p className="text-sm text-zinc-500">{a.content||a.Content||''}</p></div>)}</div></section>}
 {tab==='media'&&<section><h2 className="mb-5 text-2xl font-bold">Media</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{media.map(m=><div key={m.id} className="rounded-2xl border bg-white p-3 dark:border-zinc-800 dark:bg-zinc-900"><p className="text-sm font-semibold">{m.title||'Untitled'}</p>{m.image_url&&<img src={m.image_url} alt="" className="mt-2 aspect-[3/4] w-full rounded object-cover"/>}</div>)}</div></section>}
 </>}</main></div>;
}