import { useEffect, useState } from 'react';
import { supabase } from './supabase';
import { getAdminRole } from './adminAuth';

async function adminUser(){const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Admin session required.');const role=await getAdminRole(user.id);if(!role)throw new Error('Admin access required.');return user;}
const fmt=v=>v?new Date(v).toLocaleString('en-IN',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}):'—';

export default function AdminOperations({chapters=[]}){
 const [deleted,setDeleted]=useState([]),[logs,setLogs]=useState([]),[notifications,setNotifications]=useState([]),[subs,setSubs]=useState(0);
 const [title,setTitle]=useState(''),[body,setBody]=useState(''),[target,setTarget]=useState('all'),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const load=async()=>{try{await adminUser();const [d,l,n,s]=await Promise.all([
  supabase.from('chapters').select('id,chapter_number,title,status,deleted_at,deleted_previous_status').not('deleted_at','is',null).order('deleted_at',{ascending:false}),
  supabase.from('admin_activity_log').select('id,action,entity_type,details,created_at').order('created_at',{ascending:false}).limit(30),
  supabase.from('admin_notification_log').select('id,title,body,target,target_count,sent_count,failed_count,removed_count,status,scheduled_for,sent_at,created_at,error').order('created_at',{ascending:false}).limit(30),
  supabase.from('push_subscriptions').select('id',{count:'exact',head:true})
 ]);[d,l,n,s].forEach(x=>{if(x.error)throw x.error});setDeleted(d.data||[]);setLogs(l.data||[]);setNotifications(n.data||[]);setSubs(s.count||0);}catch(e){setNotice(e.message||'Unable to load operations data.');}};
 useEffect(()=>{load()},[]);
 const archive=async c=>{if(busy||!window.confirm(`Move ${c.chapter_number?`Chapter ${c.chapter_number}`:c.title||'this chapter'} to recovery? Nothing will be permanently deleted.`))return;setBusy(true);try{const u=await adminUser();const {error}=await supabase.from('chapters').update({deleted_at:new Date().toISOString(),deleted_previous_status:c.status||'Published',status:'Archived'}).eq('id',c.id);if(error)throw error;await supabase.from('admin_activity_log').insert({admin_user_id:u.id,action:'soft_delete_chapter',entity_type:'chapter',entity_id:c.id,details:{chapter_number:c.chapter_number,title:c.title}});setNotice('Chapter moved to recovery.');await load();}catch(e){setNotice(e.message||'Archive failed.');}finally{setBusy(false)}};
 const restore=async c=>{if(busy)return;setBusy(true);try{const u=await adminUser();const status=c.deleted_previous_status||'Draft';const {error}=await supabase.from('chapters').update({deleted_at:null,status}).eq('id',c.id);if(error)throw error;await supabase.from('admin_activity_log').insert({admin_user_id:u.id,action:'restore_chapter',entity_type:'chapter',entity_id:c.id,details:{status}});setNotice('Chapter restored.');await load();}catch(e){setNotice(e.message||'Restore failed.');}finally{setBusy(false)}};
 const send=async test=>{if(busy)return;if(!title.trim()||!body.trim()){setNotice('Add a notification title and message.');return}setBusy(true);setNotice('');try{const u=await adminUser();const actualTarget=test?`user:${u.id}`:target;const dedupeKey=`manual:${actualTarget}:${title.trim()}:${body.trim()}`;const {data,error}=await supabase.functions.invoke('send-chapter-notification-v2',{body:{title:title.trim(),body:body.trim(),target:actualTarget,dedupeKey,url:'/'}});if(error)throw error;if(!data?.ok){if(data?.duplicate)throw new Error('Duplicate notification blocked. Change the message or wait before sending again.');throw new Error(data?.error||'Notification failed.')}setNotice(`Notification sent: ${data.sent} delivered, ${data.failed} failed.`);await load();}catch(e){setNotice(e.message||'Notification failed.')}finally{setBusy(false)}};
 return <section className="admin-stack">
  {notice&&<div className="admin-card"><p>{notice}</p></div>}
  <section className="admin-card"><div className="admin-card-title"><div><span>NOTIFICATIONS</span><h2>Notification control</h2><p>{subs} registered push subscriptions · duplicate sends are blocked.</p></div></div><div className="grid gap-3 md:grid-cols-2"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Notification title" className="rounded-xl border border-zinc-700 bg-zinc-900 px-4 py-3"/><select value={target} onChange={e=>setTarget(e.target.value)} className="rounded-xl border border-zinc-700 bg-zinc-900 px-4 py-3"><option value="all">Everyone</option><option value="community">Community members</option></select><textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="Notification message" rows={3} className="rounded-xl border border-zinc-700 bg-zinc-900 px-4 py-3 md:col-span-2"/></div><div className="mt-3 flex flex-wrap gap-2"><button disabled={busy} onClick={()=>send(true)} className="rounded-xl border border-zinc-700 px-4 py-2 font-bold">Test on myself</button><button disabled={busy} onClick={()=>send(false)} className="rounded-xl bg-blue-600 px-4 py-2 font-bold">Send notification</button><button disabled={busy} onClick={load} className="rounded-xl border border-zinc-700 px-4 py-2 font-bold">Refresh</button></div></section>
  <section className="admin-card"><div className="admin-card-title"><div><span>DELIVERY</span><h2>Notification history</h2></div></div><div className="admin-chapter-list">{notifications.map(n=><article key={n.id}><div><div className="admin-status-line"><strong>{n.title}</strong><span>{n.status}</span></div><p>{n.body}</p><small>{n.target} · {n.sent_count}/{n.target_count} delivered · {n.failed_count} failed · {fmt(n.sent_at||n.created_at)}</small></div></article>)}{!notifications.length&&<p className="muted center">No notifications sent yet.</p>}</div></section>
  <section className="admin-card"><div className="admin-card-title"><div><span>RECOVERY</span><h2>Deleted chapters</h2><p>Soft-deleted chapters remain recoverable instead of being destroyed.</p></div></div><div className="admin-chapter-list">{deleted.map(c=><article key={c.id}><div><div className="admin-status-line"><strong>{c.chapter_number?`Chapter ${c.chapter_number}`:c.title||'Unnumbered'}</strong><span>Archived</span></div><p>{c.title||'Untitled'} · deleted {fmt(c.deleted_at)}</p></div><button disabled={busy} onClick={()=>restore(c)} className="rounded-xl border border-zinc-700 px-3 py-2 font-bold">Restore</button></article>)}{!deleted.length&&<p className="muted center">Recovery is empty.</p>}</div></section>
  <section className="admin-card"><div className="admin-card-title"><div><span>ADMIN AUDIT</span><h2>Activity log</h2><p>Recent important operations performed by admins.</p></div></div><div className="admin-chapter-list">{logs.map(l=><article key={l.id}><div><div className="admin-status-line"><strong>{l.action}</strong><span>{fmt(l.created_at)}</span></div><p>{l.entity_type||'system'} {l.details?.title?`· ${l.details.title}`:''}</p></div></article>)}{!logs.length&&<p className="muted center">No activity logged yet.</p>}</div></section>
  <section className="admin-card"><div className="admin-card-title"><div><span>RECOVERY ACTION</span><h2>Soft-delete a chapter</h2><p>Archive a chapter safely. Its database row and files are left intact.</p></div></div><div className="admin-chapter-list">{chapters.filter(c=>!c.deletedAt).map(c=><article key={c.id}><div><strong>{c.chapterNumber?`Chapter ${c.chapterNumber}`:'Unnumbered'} — {c.title||'Untitled'}</strong><p>{c.status||'—'}</p></div><button disabled={busy} onClick={()=>archive(c)} className="rounded-xl border border-rose-900 px-3 py-2 font-bold text-rose-300">Archive</button></article>)}</div></section>
 </section>;
}
