const STORAGE_KEY = 'atma_rekha_analytics_session';
const SESSION_KEY = 'atma_rekha_analytics_id';
const FUNNEL_EVENTS = new Set(['page_view','chapter_open','chapter_start','chapter_complete','account_created','membership_open','membership_plan_selected','checkout_started','payment_success','payment_failed','bookmark_added','rating_submitted','comment_posted']);
const EVENT_ALIASES = { membership_opened: 'membership_open' };
function getSessionId(){try{let id=sessionStorage.getItem(SESSION_KEY);if(!id){id=`${Date.now().toString(36)}-${Math.random().toString(36).slice(2,10)}`;sessionStorage.setItem(SESSION_KEY,id)}return id}catch{return 'anonymous'}}
function sanitize(value){if(value==null)return undefined;if(typeof value==='string')return value.slice(0,120);if(typeof value==='number'||typeof value==='boolean')return value;return undefined}
export function track(event,properties={}){if(!event||typeof window==='undefined')return;const normalized=EVENT_ALIASES[event]||event;const payload={event:normalized,properties:Object.fromEntries(Object.entries(properties).map(([key,value])=>[key,sanitize(value)]).filter(([,value])=>value!==undefined)),path:window.location.hash||'#home',session_id:getSessionId(),timestamp:new Date().toISOString()};window.dispatchEvent(new CustomEvent('atma:analytics',{detail:payload}));if(Array.isArray(window.dataLayer))window.dataLayer.push(payload);if(typeof window.gtag==='function')window.gtag('event',normalized,payload.properties);try{const existing=JSON.parse(sessionStorage.getItem(STORAGE_KEY)||'[]');existing.push(payload);sessionStorage.setItem(STORAGE_KEY,JSON.stringify(existing.slice(-100)))}catch{}}
export function trackPageView(){track('page_view',{page:window.location.hash||'#home'})}
function observeWebVitals(){if(typeof PerformanceObserver==='undefined')return;const report=(metric,value)=>track('web_vital',{metric,value:Math.round(value*100)/100});try{let lcp=0;const lcpObserver=new PerformanceObserver(list=>{const entries=list.getEntries();const last=entries[entries.length-1];if(last)lcp=last.startTime});lcpObserver.observe({type:'largest-contentful-paint',buffered:true});const clsObserver=new PerformanceObserver(list=>{let cls=0;for(const entry of list.getEntries())if(!entry.hadRecentInput)cls+=entry.value;if(cls)report('CLS',cls)});clsObserver.observe({type:'layout-shift',buffered:true});const inpObserver=new PerformanceObserver(list=>{for(const entry of list.getEntries())if(entry.interactionId)report('INP',entry.duration)});inpObserver.observe({type:'event',buffered:true,durationThreshold:40});const sendLcp=()=>{if(lcp)report('LCP',lcp)};if(document.visibilityState==='hidden')sendLcp();else document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')sendLcp()},{once:true})}catch{}}
function installDelegatedFunnelEvents(){let lastChapter='';document.addEventListener('click',event=>{const target=event.target.closest?.('button,a,[role="button"]');if(!target)return;if(target.matches('.rating-scale button'))track('rating_submitted',{value:target.querySelector('small')?.textContent||undefined});if(target.closest('.membership-plan')&&target.matches('button')&&!target.disabled){const text=target.textContent||'';if(/subscribe|member/i.test(text))track('membership_plan_selected',{plan_text:text.slice(0,80)})}},true);document.addEventListener('submit',event=>{if(event.target.matches('.comment-form'))track('comment_posted',{surface:'chapter_comments'})},true);const observeRoute=()=>{const hash=window.location.hash||'#home';const chapter=hash.match(/^#read-chapter\/([^/?#]+)/i)?.[1];if(chapter&&chapter!==lastChapter){lastChapter=chapter;track('chapter_open',{chapter_id:decodeURIComponent(chapter)});track('chapter_start',{chapter_id:decodeURIComponent(chapter)})}else if(!chapter)lastChapter='';if(/^#membership(?:\/|$)/i.test(hash))track('membership_open');};observeRoute();window.addEventListener('hashchange',observeRoute,{passive:true})}
export function installAnalytics(){let last='';const send=()=>{const current=window.location.hash||'#home';if(current===last)return;last=current;trackPageView()};send();observeWebVitals();installDelegatedFunnelEvents();window.addEventListener('hashchange',send,{passive:true});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')send()},{passive:true});return()=>window.removeEventListener('hashchange',send)}
if(typeof window!=='undefined')window.atmaAnalytics={track,trackPageView,funnelEvents:[...FUNNEL_EVENTS]};
