import { useEffect, useState } from 'react';
import { supabase } from './supabase';

export default function CommunityAdmin() {
  const [open, setOpen] = useState(false); const [title, setTitle] = useState(''); const [content, setContent] = useState(''); const [pinned, setPinned] = useState(false); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(''); const [visible, setVisible] = useState(false);
  useEffect(() => { const scan = () => { const text = document.body.innerText || ''; setVisible(/Admin Panel|Admin access|Dashboard/i.test(text) && !window.location.hash.includes('community')); }; scan(); const observer = new MutationObserver(scan); observer.observe(document.body, { childList: true, subtree: true }); return () => observer.disconnect(); }, []);
  if (!visible) return null;
  const publish = async event => { event.preventDefault(); if (!content.trim() || busy) return; setBusy(true); setNotice(''); try { const { data: { user } } = await supabase.auth.getUser(); if (!user) throw new Error('Admin session required.'); const { data: admin } = await supabase.from('admins').select('user_id').eq('user_id', user.id).maybeSingle(); if (!admin) throw new Error('Admin access required.'); const { error } = await supabase.from('community_posts').insert({ title: title.trim() || null, content: content.trim(), is_pinned: pinned, published_at: new Date().toISOString() }); if (error) throw error; setTitle(''); setContent(''); setPinned(false); setNotice('Message published to Community.'); } catch (error) { setNotice(error.message || 'Unable to publish.'); } finally { setBusy(false); } };
  return <><button className="community-admin-launch" onClick={() => setOpen(true)}>📣 Community</button>{open && <div className="community-admin-backdrop" onMouseDown={e => e.target === e.currentTarget && setOpen(false)}><section className="community-admin-modal"><div className="community-admin-head"><div><p>CREATOR CHANNEL</p><h2>Community</h2></div><button onClick={() => setOpen(false)}>×</button></div><p className="community-admin-sub">Send a broadcast message that every reader can see.</p><form onSubmit={publish}><input value={title} onChange={e => setTitle(e.target.value.slice(0,120))} placeholder="Optional title"/><textarea value={content} onChange={e => setContent(e.target.value.slice(0,4000))} placeholder="Write your message…" rows="6" required/><label><input type="checkbox" checked={pinned} onChange={e => setPinned(e.target.checked)}/> Pin this message</label>{notice && <p className="community-admin-notice">{notice}</p>}<button className="community-admin-send" disabled={busy}>{busy ? 'Publishing…' : 'Publish to Community'}</button></form></section></div>}</>;
}
