import { useEffect, useState } from 'react';
import { supabase } from './supabase';

function relativeTime(value) { const diff = Math.max(0, Date.now() - new Date(value).getTime()); const mins = Math.floor(diff / 60000); if (mins < 1) return 'just now'; if (mins < 60) return `${mins}m`; const hours = Math.floor(mins / 60); if (hours < 24) return `${hours}h`; const days = Math.floor(hours / 24); if (days < 30) return `${days}d`; return new Date(value).toLocaleDateString('en-IN', { day: 'numeric', month: 'short' }); }

export default function CommunityPage() {
  const [posts, setPosts] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async () => { setLoading(true); const { data, error } = await supabase.from('community_posts').select('id,title,content,image_url,is_pinned,published_at,created_at').order('is_pinned', { ascending: false }).order('published_at', { ascending: false }); if (error) setError(error.message); else setPosts(data || []); setLoading(false); };
  useEffect(() => { if (window.location.hash !== '#community') return; load(); const onHash = () => { if (window.location.hash === '#community') load(); }; window.addEventListener('hashchange', onHash); return () => window.removeEventListener('hashchange', onHash); }, []);
  if (window.location.hash !== '#community') return null;
  return <div className="community-page"><header className="community-header"><a href="#index" className="community-back">←</a><div><p>ATMA REKHA</p><h1>Community</h1></div><span className="community-live">● LIVE</span></header><main className="community-feed"><section className="community-welcome"><div className="community-mark">✦</div><div><p className="community-kicker">THE ATMA REKHA CHANNEL</p><h2>Stay close to the story.</h2><p>Updates, thoughts, behind-the-scenes moments and messages from the creator — all in one place.</p></div></section>{loading ? <div className="community-empty">Loading the channel…</div> : error ? <div className="community-empty">Unable to load the community right now.</div> : !posts.length ? <div className="community-empty"><strong>The channel is quiet for now.</strong><span>New messages will appear here when the creator posts.</span></div> : <div className="community-posts">{posts.map(post => <article className={`community-post${post.is_pinned ? ' pinned' : ''}`} key={post.id}>{post.image_url && <img src={post.image_url} alt=""/>}<div className="community-post-body"><div className="community-post-meta"><span>{post.is_pinned ? '📌 Pinned' : 'Atma Rekha'}</span><time>{relativeTime(post.published_at || post.created_at)}</time></div>{post.title && <h3>{post.title}</h3>}<p>{post.content}</p><div className="community-post-footer"><span>✦ Creator message</span><button type="button" onClick={() => navigator.clipboard?.writeText(post.content)}>Share ↗</button></div></div></article>)}</div>}</main></div>;
}
