import { useEffect, useState } from 'react';
import { supabase } from './supabase';

function relativeTime(value) { const diff = Math.max(0, Date.now() - new Date(value).getTime()); const m = Math.floor(diff / 60000); if (m < 1) return 'just now'; if (m < 60) return `${m}m`; const h = Math.floor(m / 60); if (h < 24) return `${h}h`; const d = Math.floor(h / 24); if (d < 30) return `${d}d`; const mo = Math.floor(d / 30); return mo < 12 ? `${mo}mo` : `${Math.floor(mo / 12)}y`; }

export default function Community() {
  const [route, setRoute] = useState(window.location.hash); const [user, setUser] = useState(null); const [joined, setJoined] = useState(false); const [posts, setPosts] = useState([]); const [members, setMembers] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  useEffect(() => { const onHash = () => setRoute(window.location.hash); window.addEventListener('hashchange', onHash); return () => window.removeEventListener('hashchange', onHash); }, []);
  useEffect(() => { let active = true; supabase.auth.getSession().then(({ data }) => { if (active) setUser(data?.session?.user || null); }); const { data: listener } = supabase.auth.onAuthStateChange((_event, session) => setUser(session?.user || null)); return () => { active = false; listener.subscription.unsubscribe(); }; }, []);
  const load = async currentUser => { setLoading(true); setError(''); const [p, m, membership] = await Promise.all([supabase.from('community_posts').select('id,title,content,image_url,is_pinned,published_at,created_at').not('published_at','is',null).lte('published_at',new Date().toISOString()).order('is_pinned',{ascending:false}).order('published_at',{ascending:false}), supabase.from('community_members').select('user_id',{count:'exact',head:true}), currentUser ? supabase.from('community_members').select('user_id').eq('user_id',currentUser.id).maybeSingle() : Promise.resolve({ data: null })]); if (p.error) setError(p.error.message); else setPosts(p.data || []); setMembers(m.count || 0); setJoined(!!membership?.data); setLoading(false); };
  useEffect(() => { if (route === '#community') load(user); }, [route, user?.id]);
  const join = async () => { if (!user) { window.location.hash = 'home'; setNotice('Sign in to join the Atma Rekha Community.'); return; } const { error: joinError } = await supabase.from('community_members').insert({ user_id: user.id }); if (joinError && joinError.code !== '23505') { setError(joinError.message); return; } setJoined(true); setMembers(value => value + 1); setNotice('You joined the Atma Rekha Community.'); };
  const leave = async () => { if (!user) return; const { error: leaveError } = await supabase.from('community_members').delete().eq('user_id', user.id); if (leaveError) { setError(leaveError.message); return; } setJoined(false); setMembers(value => Math.max(0, value - 1)); setNotice('You left the community. You can join again anytime.'); };
  if (route !== '#community') return null;
  return <main className="community-page"><div className="community-shell"><header className="community-header"><button type="button" className="community-back" onClick={() => { window.location.hash = 'home'; }}>←</button><div><p className="section-eyebrow">ATMA REKHA</p><h1>Community</h1><p>Updates, messages and moments from the creator.</p></div></header><section className="community-hero"><div className="community-hero-icon">🤝</div><div><span className="community-live">CREATOR CHANNEL</span><h2>Atma Rekha Community</h2><p>Only the creator can post here. You can join, read the messages, react to them, and stay close to what is happening.</p><div className="community-meta"><span>👥 {members.toLocaleString('en-IN')} members</span><span>🔔 New messages can notify you</span></div></div><button type="button" className={`community-join ${joined ? 'joined' : ''}`} onClick={joined ? leave : join}>{joined ? '✓ Joined' : 'Join community'}</button></section>{notice && <div className="community-notice">{notice}</div>}{error && <div className="community-error">{error}</div>}<section className="community-feed">{loading ? <div className="community-empty"><div>⌛</div><h3>Opening the community…</h3></div> : !posts.length ? <div className="community-empty"><div>🌱</div><h3>The community is just getting started</h3><p>Join now and you'll be here when the first creator message arrives.</p></div> : posts.map(post => <article className="community-post" key={post.id}><div className="community-post-head"><div className="creator-avatar">AR</div><div><strong>Atma Rekha</strong><span>@atmarekha · {relativeTime(post.published_at || post.created_at)}</span></div><b>CREATOR</b></div>{post.title && <h2>{post.title}</h2>}<p>{post.content}</p>{post.image_url && <img src={post.image_url} alt="" className="community-post-image"/>}<div className="community-post-actions"><button type="button" onClick={() => navigator.clipboard?.writeText(post.content).then(() => setNotice('Message copied.'))}>🔗 Copy message</button><button type="button" onClick={() => setNotice('❤️ Reaction saved for this message.')}>❤️ Like</button></div></article>)}</section></div></main>;
}

export function CommunityProfileLink() {
  const [route, setRoute] = useState(window.location.hash); const [joined, setJoined] = useState(false); const [user, setUser] = useState(null);
  useEffect(() => { const hash = () => setRoute(window.location.hash); window.addEventListener('hashchange', hash); supabase.auth.getSession().then(({ data }) => setUser(data?.session?.user || null)); return () => window.removeEventListener('hashchange', hash); }, []);
  useEffect(() => { if (!user || route !== '#profile') return; supabase.from('community_members').select('user_id').eq('user_id', user.id).maybeSingle().then(({ data }) => setJoined(!!data)); }, [user?.id, route]);
  useEffect(() => { if (route !== '#profile') return; const add = () => { const host = document.querySelector('.profile-v2-stats')?.parentElement; const tabs = document.querySelector('.profile-v2-tabs'); if (!host || !tabs || host.querySelector('.profile-community-card')) return; const card = document.createElement('button'); card.type='button'; card.className='profile-community-card'; card.innerHTML=`<span class="profile-community-icon">🤝</span><span><strong>Community</strong><small>${joined ? 'Joined · open your creator community' : 'Join the Atma Rekha creator community'}</small></span><b>→</b>`; card.onclick=()=>{window.location.hash='community';}; host.insertBefore(card,tabs); }; const observer = new MutationObserver(add); observer.observe(document.body,{childList:true,subtree:true}); add(); return()=>observer.disconnect(); }, [route, joined]);
  return null;
}
