import { useEffect, useState } from 'react';
import { supabase } from './supabase';

const relativeTime = value => { const d=Math.max(0,Date.now()-new Date(value).getTime()); const m=Math.floor(d/60000); if(m<1)return 'just now'; if(m<60)return `${m}m`; const h=Math.floor(m/60); if(h<24)return `${h}h`; const days=Math.floor(h/24); if(days<30)return `${days}d`; const mo=Math.floor(days/30); return mo<12?`${mo}mo`:`${Math.floor(mo/12)}y`; };

export default function Community(){
  const [route,setRoute]=useState(location.hash),[user,setUser]=useState(null),[posts,setPosts]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[reactions,setReactions]=useState({}),[reactionBusy,setReactionBusy]=useState(null);
  useEffect(()=>{const h=()=>setRoute(location.hash);addEventListener('hashchange',h);supabase.auth.getSession().then(({data})=>setUser(data?.session?.user||null));const{data:l}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user||null));return()=>{removeEventListener('hashchange',h);l.subscription.unsubscribe()}},[]);
  const load=async currentUser=>{setLoading(true);setError('');const{data:rows,error:pError}=await supabase.from('community_posts').select('id,title,content,image_url,attachment_url,attachment_name,attachment_type,attachment_size,is_pinned,published_at,created_at').not('published_at','is',null).lte('published_at',new Date().toISOString()).order('is_pinned',{ascending:false}).order('published_at',{ascending:false});if(pError)setError(pError.message);else{setPosts(rows||[]);const ids=(rows||[]).map(r=>r.id);if(ids.length){const{data:r,error:re}=await supabase.from('community_post_reactions').select('post_id,user_id,reaction').in('post_id',ids);if(re)setError(re.message);const state={};for(const x of r||[]){const key=x.post_id;state[key]??={count:0,reacted:false};state[key].count++;if(currentUser?.id===x.user_id)state[key].reacted=true}setReactions(state)}}setLoading(false)};
  useEffect(()=>{if(route==='#community')load(user)},[route,user?.id]);
  const react=async post=>{if(!user){setNotice('Sign in to react to community messages.');return}if(reactionBusy)return;setReactionBusy(post.id);try{const current=reactions[post.id]?.reacted;if(current){const{error:e}=await supabase.from('community_post_reactions').delete().eq('post_id',post.id).eq('user_id',user.id).eq('reaction','heart');if(e)throw e;setReactions(p=>({...p,[post.id]:{count:Math.max(0,(p[post.id]?.count||1)-1),reacted:false}}))}else{const{error:e}=await supabase.from('community_post_reactions').insert({post_id:post.id,user_id:user.id,reaction:'heart'});if(e&&e.code!=='23505')throw e;setReactions(p=>({...p,[post.id]:{count:(p[post.id]?.count||0)+1,reacted:true}}))}}catch(e){setError(e.message||'Unable to save reaction.')}finally{setReactionBusy(null)}};
  const share=async post=>{try{if(navigator.share)await navigator.share({title:post.title||'Atma Rekha Community',text:post.content,url:`${location.origin}${location.pathname}#community`});else{await navigator.clipboard?.writeText(post.content);setNotice('Message copied.')}}catch(e){if(e?.name!=='AbortError')setError('Sharing is unavailable on this device.')}};
  if(route!=='#community')return null;
  return <main className="community-page"><div className="community-shell"><header className="community-header"><button type="button" className="community-back" onClick={()=>location.hash='profile'}>←</button><div><h1>🤝 Welcome to Atma Rekha Community</h1><p>Welcome! This is the place where I’ll share updates, announcements, behind-the-scenes moments, and messages directly with you.</p><p>Everyone is welcome to read. No joining is required.</p></div></header>{notice&&<div className="community-notice">{notice}</div>}{error&&<div className="community-error">{error}</div>}<section className="community-feed">{loading?<div className="community-empty"><div>⌛</div><h3>Opening the community…</h3></div>:!posts.length?<div className="community-empty"><div>🌱</div><h3>The community is just getting started</h3><p>The first creator message will appear here.</p></div>:posts.map(post=><article className={`community-post ${post.is_pinned?'is-pinned':''}`} key={post.id}>{post.is_pinned&&<div className="community-pinned">📌 Pinned message</div>}<div className="community-post-head"><div className="creator-avatar">AR</div><div><strong>Atma Rekha</strong><span>@atmarekha · {relativeTime(post.published_at||post.created_at)}</span></div><b>CREATOR</b></div>{post.title&&<h2>{post.title}</h2>}<p>{post.content}</p>{post.image_url&&<img src={post.image_url} alt="" className="community-post-image" loading="lazy"/>}{post.attachment_url&&<a className="community-attachment" href={post.attachment_url} target="_blank" rel="noreferrer">📎 <span><strong>{post.attachment_name||'Attachment'}</strong><small>{post.attachment_type||'File'}{post.attachment_size?` · ${(post.attachment_size/1024/1024).toFixed(1)} MB`:''}</small></span>↗</a>}<div className="community-post-actions"><button type="button" onClick={()=>react(post)} className={reactions[post.id]?.reacted?'reacted':''}>❤️ {reactions[post.id]?.count||0}</button><button type="button" onClick={()=>share(post)}>↗ Share</button><button type="button" onClick={()=>{navigator.clipboard?.writeText(post.content);setNotice('Message copied.')}}>🔗 Copy</button></div></article>)}</section></div></main>;
}

export function CommunityProfileLink(){return null}
