import { useEffect, useMemo, useState } from 'react';
import { supabase, getCurrentMemberships } from './supabase';
import SubscriberBadge from './SubscriberBadge.jsx';
import { fetchChapterComments, fetchCommentLikes, getViewerKey, likeComment, unlikeComment, reportComment, addComment } from './engagement';

const ago = value => { const d = Math.max(0, Date.now() - new Date(value).getTime()); const m = Math.floor(d / 60000); if (m < 1) return 'just now'; if (m < 60) return `${m}m`; const h = Math.floor(m / 60); if (h < 24) return `${h}h`; const days = Math.floor(h / 24); if (days < 30) return `${days}d`; if (days < 365) return `${Math.floor(days / 30)}mo`; return `${Math.floor(days / 365)}y`; };
const profileLabel = p => p?.username || 'reader';
const friendlyError = (error, fallback = 'Something went wrong. Please try again.') => { const raw = String(error?.message || error || '').toLowerCase(); if (!raw || raw.includes('jwt') || raw.includes('auth') || raw.includes('permission denied') || raw.includes('row-level security') || raw.includes('rls') || raw.includes('profiles') || raw.includes('not authenticated') || raw.includes('unauthorized')) { if (raw.includes('auth') || raw.includes('jwt') || raw.includes('not authenticated') || raw.includes('unauthorized') || raw.includes('permission denied')) return 'Please log in to do this action.'; return fallback; } return fallback; };
function getChapterId(button) { const row = button?.closest?.('.chapter-row'); const href = row?.querySelector?.('.chapter-row-main')?.getAttribute('href'); if (href?.includes('read-chapter/')) return decodeURIComponent(href.split('read-chapter/')[1]); const hash = window.location.hash || ''; if (hash.includes('read-chapter/')) return decodeURIComponent(hash.split('read-chapter/')[1].split('/')[0]); return null; }

export default function EnhancedComments() {
  const [open,setOpen]=useState(false),[chapterId,setChapterId]=useState(null),[comments,setComments]=useState([]),[profiles,setProfiles]=useState({}),[membershipPlans,setMembershipPlans]=useState(new Map()),[likes,setLikes]=useState({counts:{},liked:{}}),[user,setUser]=useState(null),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[text,setText]=useState(''),[replyTo,setReplyTo]=useState(null),[preview,setPreview]=useState(null),[copied,setCopied]=useState(null),[reporting,setReporting]=useState(null);
  useEffect(()=>{let active=true;supabase.auth.getSession().then(({data})=>{if(active)setUser(data?.session?.user||null)});const {data:listener}=supabase.auth.onAuthStateChange((_e,session)=>setUser(session?.user||null));return()=>{active=false;listener.subscription.unsubscribe()}},[]);
  useEffect(()=>{const handler=event=>{const button=event.target?.closest?.('button');if(!button)return;const label=`${button.getAttribute('aria-label')||''} ${button.getAttribute('title')||''} ${button.textContent||''}`.toLowerCase();if(!label.includes('comments'))return;const id=getChapterId(button);if(!id)return;event.preventDefault();event.stopPropagation();event.stopImmediatePropagation?.();setChapterId(id);setOpen(true)};document.addEventListener('click',handler,true);return()=>document.removeEventListener('click',handler,true)},[]);
  const load=async()=>{if(!chapterId)return;setLoading(true);setError('');try{const rows=await fetchChapterComments(chapterId);setComments(rows);setLikes(await fetchCommentLikes(rows.map(r=>r.id)));const ids=[...new Set(rows.map(r=>r.user_id).filter(Boolean))];if(user?.id)ids.push(user.id);if(ids.length){const uniqueIds=[...new Set(ids)];const {data,error:e}=await supabase.from('profiles').select('id,username,display_name,avatar_url,bio,created_at').in('id',uniqueIds);if(e)throw e;setProfiles(Object.fromEntries((data||[]).map(p=>[p.id,p])));try{setMembershipPlans(await getCurrentMemberships(uniqueIds))}catch(subscriptionError){console.warn('Membership lookup failed:',subscriptionError);setMembershipPlans(new Map())}}else{setProfiles({});setMembershipPlans(new Map())}}catch(e){setError(friendlyError(e,'We couldn’t load the comments right now. Please try again.'))}finally{setLoading(false)}};
  useEffect(()=>{if(open&&chapterId)load()},[open,chapterId,user?.id]);
  const top=useMemo(()=>comments.filter(c=>!c.parent_comment_id),[comments]); const child=useMemo(()=>comments.filter(c=>c.parent_comment_id),[comments]); const profile=id=>profiles[id]||null;
  const goProfile=id=>{if(id)window.location.hash=`public-profile/${encodeURIComponent(id)}`};
  const ensureAuth=()=>{if(user)return true;setError('Please log in to do this action.');return false};
  const post=async event=>{event.preventDefault();if(!ensureAuth()||busy)return;const clean=text.trim();if(!clean)return;setBusy(true);setError('');try{const row=await addComment({chapterId,content:clean,parentCommentId:replyTo});setComments(p=>[...p,row]);setText('');setReplyTo(null)}catch(e){setError(friendlyError(e,'We couldn’t post your comment. Please try again.'))}finally{setBusy(false)}};
  const toggleLike=async comment=>{if(!ensureAuth())return;const liked=!!likes.liked[comment.id];try{if(liked){await unlikeComment(comment.id);setLikes(p=>({counts:{...p.counts,[comment.id]:Math.max(0,(p.counts[comment.id]||1)-1)},liked:{...p.liked,[comment.id]:false}}))}else{await likeComment(comment.id);setLikes(p=>({counts:{...p.counts,[comment.id]:(p.counts[comment.id]||0)+1},liked:{...p.liked,[comment.id]:true}}))}}catch(e){setError(friendlyError(e,'We couldn’t update the reaction. Please try again.'))}};
  const copy=async comment=>{try{const shareText=`${comment.content}\n— Atma Rekha Community`;if(navigator.share){await navigator.share({text:shareText})}else{await navigator.clipboard?.writeText(shareText);setCopied(comment.id);setTimeout(()=>setCopied(null),1400)}}catch(e){if(e?.name!=='AbortError')setError('Sharing is unavailable on this device.')}};
  const report=async comment=>{if(reporting===comment.id)return;setReporting(comment.id);try{await reportComment(comment.id);setError('Thanks. The comment has been reported.')}catch(e){setError(friendlyError(e,'We couldn’t report this comment. Please try again.'))}finally{setReporting(null)}};
  if(!open)return null;
  return <div className="ec-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><section className="ec-sheet" role="dialog" aria-modal="true" aria-label="Comments"><header className="ec-header"><div><h2>Comments <span>{comments.length}</span></h2></div><button className="ec-close" onClick={()=>setOpen(false)} aria-label="Close">×</button></header>{!user&&<div className="ec-join"><div className="ec-join-icon">✦</div><div><strong>Join the community</strong><p>Reading is free. Create a free account to comment, reply and react.</p></div><button onClick={()=>{setOpen(false);window.location.hash='home';setTimeout(()=>Array.from(document.querySelectorAll('button')).find(b=>/sign in/i.test(b.textContent||''))?.click(),150)}}>Join free</button></div>}{loading?<div className="ec-state">Opening comments…</div>:error&&!comments.length?<div className="ec-state"><strong>We couldn’t load the comments.</strong><span>{error}</span></div>:!top.length?<div className="ec-empty"><div>💬</div><strong>Start the first comment</strong><p>No comments yet. Be the first reader to leave a thought.</p></div>:<div className="ec-list">{top.map(comment=><CommentCard key={comment.id} comment={comment} replies={child.filter(r=>r.parent_comment_id===comment.id)} profile={profile(comment.user_id)} user={user} likes={likes} onLike={toggleLike} onReply={id=>{setReplyTo(id);setText('')}} onCopy={copy} copied={copied} onReport={report} onProfile={goProfile} onPreview={setPreview} profileFor={profile} membershipPlans={membershipPlans}/>)}</div>}{error&&comments.length>0&&<div className="ec-notice">{error}</div>}<form className="ec-composer" onSubmit={post}>{replyTo&&<div className="ec-replying"><span>Replying to a reader</span><button type="button" onClick={()=>{setReplyTo(null);setText('')}}>Cancel</button></div>}<div className="ec-compose-row"><Avatar profile={profile(user?.id)} fallback={user?'R':'👤'}/><textarea value={text} onChange={e=>setText(e.target.value.slice(0,2000))} placeholder={!user?'Sign in to write a comment':replyTo?'Write your reply…':'Share your thoughts…'} disabled={!user} rows="2"/><button disabled={busy||!user||!text.trim()}>{busy?'…':replyTo?'↩':'➤'}</button></div></form>{preview&&<ProfilePreview profile={preview} membershipPlan={membershipPlans.get(preview?.id)} onClose={()=>setPreview(null)} onOpen={()=>{setPreview(null);goProfile(preview.id)}}/>}</section></div>;
}
function Avatar({profile,fallback}){return profile?.avatar_url?<img className="ec-avatar" src={profile.avatar_url} alt=""/>:<div className="ec-avatar ec-avatar-fallback">{fallback||'R'}</div>}
function CommentCard({comment,replies,profile,user,likes,onLike,onReply,onCopy,copied,onReport,onProfile,onPreview,profileFor,membershipPlans}){const name=profileLabel(profile);return <article className="ec-comment"><button className="ec-avatar-button" onClick={()=>onPreview(profile||{id:comment.user_id,username:'reader'})}><Avatar profile={profile} fallback={name.slice(0,1).toUpperCase()}/></button><div className="ec-comment-main"><div className="ec-meta"><div><button className="ec-username" onClick={()=>onProfile(comment.user_id)}>@{profile?.username||'reader'}<SubscriberBadge planId={membershipPlans.get(comment.user_id)} /></button></div><time>{ago(comment.created_at)}{comment.updated_at&&new Date(comment.updated_at).getTime()>new Date(comment.created_at).getTime()+1000?' · edited':''}</time></div><p className="ec-content">{comment.content}</p><div className="ec-actions"><button onClick={()=>onLike(comment)} className={likes.liked[comment.id]?'liked':''}>♥ {likes.counts[comment.id]||0}</button><button onClick={()=>onReply(comment.id)}>↩ Reply</button><button onClick={()=>onCopy(comment)}>{copied===comment.id?'✓ Shared':'↗ Share'}</button>{user&&user.id!==comment.user_id&&<button onClick={()=>onReport(comment)}>⚑ Report</button>}</div>{replies.length>0&&<div className="ec-replies">{replies.map(reply=><CommentCard key={reply.id} comment={reply} replies={[]} profile={profileFor(reply.user_id)} user={user} likes={likes} onLike={onLike} onReply={onReply} onCopy={onCopy} copied={copied} onReport={onReport} onProfile={onProfile} onPreview={onPreview} profileFor={profileFor} membershipPlans={membershipPlans}/>)}</div>}</div></article>}
function ProfilePreview({profile,membershipPlan,onClose,onOpen}){return <div className="ec-preview-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="ec-preview"><button className="ec-preview-close" onClick={onClose}>×</button><Avatar profile={profile}/><strong>{profile?.username||'reader'}<SubscriberBadge planId={membershipPlan}/></strong><span>@{profile?.username||'reader'}</span>{profile?.bio&&<p>{profile.bio}</p>}<small>Public reader profile</small><button className="ec-preview-open" onClick={onOpen}>View profile</button></section></div>}