import { useEffect, useMemo, useState } from 'react';
import { supabase } from './supabase';
import { fetchChapterComments, fetchCommentLikes, getViewerKey, likeComment, reportComment } from './engagement';

const fallbackAvatar = '◉';
const ago = value => { const t = new Date(value).getTime(); const d = Math.max(0, Date.now() - t); const m = Math.floor(d / 60000); if (m < 1) return 'just now'; if (m < 60) return `${m}m`; const h = Math.floor(m / 60); if (h < 24) return `${h}h`; const days = Math.floor(h / 24); if (days < 30) return `${days}d`; if (days < 365) return `${Math.floor(days / 30)}mo`; return `${Math.floor(days / 365)}y`; };
const profileLabel = p => p?.display_name || p?.username || 'Reader';
function getChapterId(button) { const row = button?.closest?.('.chapter-row'); const href = row?.querySelector?.('.chapter-row-main')?.getAttribute('href'); if (href?.includes('read-chapter/')) return decodeURIComponent(href.split('read-chapter/')[1]); const hash = window.location.hash || ''; if (hash.includes('read-chapter/')) return decodeURIComponent(hash.split('read-chapter/')[1].split('/')[0]); return null; }

export default function EnhancedComments() {
  const [open,setOpen]=useState(false),[chapterId,setChapterId]=useState(null),[comments,setComments]=useState([]),[profiles,setProfiles]=useState({}),[likes,setLikes]=useState({counts:{},liked:{}}),[user,setUser]=useState(null),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[text,setText]=useState(''),[replyTo,setReplyTo]=useState(null),[preview,setPreview]=useState(null),[copied,setCopied]=useState(null),[reporting,setReporting]=useState(null);
  useEffect(()=>{let active=true;supabase.auth.getSession().then(({data})=>{if(active)setUser(data?.session?.user||null)});const {data:listener}=supabase.auth.onAuthStateChange((_e,session)=>setUser(session?.user||null));return()=>{active=false;listener.subscription.unsubscribe()}},[]);
  useEffect(()=>{const handler=event=>{const button=event.target?.closest?.('button');if(!button)return;const label=`${button.getAttribute('aria-label')||''} ${button.getAttribute('title')||''} ${button.textContent||''}`.toLowerCase();if(!label.includes('comments'))return;const id=getChapterId(button);if(!id)return;event.preventDefault();event.stopPropagation();event.stopImmediatePropagation?.();setChapterId(id);setOpen(true)};document.addEventListener('click',handler,true);return()=>document.removeEventListener('click',handler,true)},[]);
  useEffect(()=>{if(!open||!chapterId)return;let active=true;(async()=>{setLoading(true);setError('');try{const rows=await fetchChapterComments(chapterId);if(!active)return;setComments(rows);setLikes(await fetchCommentLikes(rows.map(row=>row.id)));const ids=[...new Set(rows.map(row=>row.user_id).filter(Boolean))];if(ids.length){const {data,error:profileError}=await supabase.from('profiles').select('id,username,display_name,avatar_url,bio,created_at').in('id',ids);if(profileError)throw profileError;setProfiles(Object.fromEntries((data||[]).map(p=>[p.id,p])))}else setProfiles({})}catch(e){if(active)setError(e?.message||'Unable to load the conversation.')}finally{if(active)setLoading(false)}})();return()=>{active=false}},[open,chapterId]);
  const top=useMemo(()=>comments.filter(c=>!c.parent_comment_id),[comments]),child=useMemo(()=>comments.filter(c=>c.parent_comment_id),[comments]);
  const profile=id=>profiles[id]||null; const goProfile=id=>{if(id)window.location.hash=`public-profile/${encodeURIComponent(id)}`};
  const post=async event=>{event.preventDefault();if(!user){setError('Sign in to join the conversation.');return}const clean=text.trim();if(!clean||busy)return;setBusy(true);setError('');try{const {data,error:insertError}=await supabase.from('comments').insert({user_id:user.id,chapter_id:chapterId,author_name:profile(user.id)?.display_name||profile(user.id)?.username||user.email?.split('@')[0]||'Reader',content:clean,parent_comment_id:replyTo}).select('id,user_id,chapter_id,author_name,content,created_at,updated_at,parent_comment_id').single();if(insertError)throw insertError;setComments(previous=>[...previous,data]);setText('');setReplyTo(null)}catch(e){setError(e?.message||'Unable to post your comment.')}finally{setBusy(false)}};
  const toggleLike=async comment=>{if(!user){setError('Sign in to like comments.');return}const liked=!!likes.liked[comment.id];try{if(liked){const {error}=await supabase.from('comment_likes').delete().eq('comment_id',comment.id).eq('viewer_key',getViewerKey());if(error)throw error;setLikes(p=>({counts:{...p.counts,[comment.id]:Math.max(0,(p.counts[comment.id]||1)-1)},liked:{...p.liked,[comment.id]:false}}))}else{await likeComment(comment.id);setLikes(p=>({counts:{...p.counts,[comment.id]:(p.counts[comment.id]||0)+1},liked:{...p.liked,[comment.id]:true}}))}}catch(e){setError(e?.message||'Unable to update reaction.')}};
  const copy=async comment=>{try{const shareText=`${comment.content}\n— Atma Rekha Community`;if(navigator.share){await navigator.share({text:shareText})}else{await navigator.clipboard?.writeText(shareText);setCopied(comment.id);setTimeout(()=>setCopied(null),1400)}}catch(e){if(e?.name!=='AbortError')setError('Sharing is unavailable on this device.')}};
  const report=async comment=>{if(reporting===comment.id)return;setReporting(comment.id);try{await reportComment(comment.id);setError('Thanks. The comment has been reported.')}catch(e){setError(e?.message||'Unable to report this comment.')}finally{setReporting(null)}};
  const remove=async comment=>{if(!user||comment.user_id!==user.id)return;if(!window.confirm('Delete this comment?'))return;const {error:deleteError}=await supabase.from('comments').delete().eq('id',comment.id).eq('user_id',user.id);if(deleteError){setError(deleteError.message);return}setComments(previous=>previous.filter(c=>c.id!==comment.id&&c.parent_comment_id!==comment.id))};
  if(!open)return null;
  return <div className="ec-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><section className="ec-sheet" role="dialog" aria-modal="true" aria-label="Chapter community"><header className="ec-header"><div><p className="ec-eyebrow">ATMA REKHA COMMUNITY</p><h2>Reader conversation <span>{comments.length}</span></h2><p>A place for readers to share reactions, questions and favourite moments.</p></div><button className="ec-close" onClick={()=>setOpen(false)} aria-label="Close">×</button></header>{!user&&<div className="ec-join"><div className="ec-join-icon">✦</div><div><strong>Join the conversation</strong><p>Reading is free. Create an account when you're ready to leave your own mark.</p></div><button onClick={()=>{setOpen(false);window.location.hash='home';setTimeout(()=>Array.from(document.querySelectorAll('button')).find(b=>/sign in/i.test(b.textContent||''))?.click(),150)}}>Join free</button></div>}<div className="ec-list">{loading?<div className="ec-state">Opening the conversation…</div>:error&&!comments.length?<div className="ec-state"><strong>We couldn't load the conversation.</strong><span>{error}</span></div>:!top.length?<div className="ec-empty"><div>💬</div><strong>Start the first conversation</strong><p>No comments yet. Share what you noticed, what surprised you, or the moment that stayed with you.</p>{!user&&<button onClick={()=>{setOpen(false);window.location.hash='home'}}>Create your free account</button>}</div>:top.map(comment=><CommentCard key={comment.id} comment={comment} replies={child.filter(r=>r.parent_comment_id===comment.id)} profile={profile(comment.user_id)} user={user} likes={likes} onLike={toggleLike} onReply={setReplyTo} onCopy={copy} copied={copied} onReport={report} onDelete={remove} onProfile={goProfile} onPreview={setPreview} profileFor={profile}/>)}</div>{error&&comments.length>0&&<div className="ec-notice">{error}</div>}<form className="ec-composer" onSubmit={post}>{replyTo&&<div className="ec-replying">Replying to a reader <button type="button" onClick={()=>setReplyTo(null)}>Cancel</button></div>}<div className="ec-compose-row"><Avatar profile={profile(user?.id)} fallback={user?'R':'👤'}/><textarea value={text} onChange={e=>setText(e.target.value.slice(0,2000))} placeholder={user?(replyTo?'Write your reply…':'Share your thoughts…'):'Sign in to write a comment'} disabled={!user} rows="2"/><button disabled={busy||!user||!text.trim()}>{busy?'…':'➤'}</button></div></form>{preview&&<ProfilePreview profile={preview} onClose={()=>setPreview(null)} onOpen={()=>{setPreview(null);goProfile(preview.id)}}/>}</section></div>;
}
function Avatar({profile,fallback}){return profile?.avatar_url?<img className="ec-avatar" src={profile.avatar_url} alt=""/>:<div className="ec-avatar ec-avatar-fallback">{fallback||fallbackAvatar}</div>}
function CommentCard({comment,replies,profile,user,likes,onLike,onReply,onCopy,copied,onReport,onDelete,onProfile,onPreview,profileFor}){const name=profileLabel(profile)||comment.author_name||'Reader';return <article className="ec-comment"><button className="ec-avatar-button" onClick={()=>onPreview(profile||{id:comment.user_id,username:comment.author_name})}><Avatar profile={profile} fallback={(name||'R').slice(0,1).toUpperCase()}/></button><div className="ec-comment-main"><div className="ec-meta"><div><button className="ec-username" onClick={()=>onProfile(comment.user_id)}>@{profile?.username||(comment.author_name||'reader').replace(/\s+/g,'').toLowerCase()}</button>{profile?.display_name&&<strong>{profile.display_name}</strong>}</div><time>{ago(comment.created_at)}</time></div><p className="ec-content">{comment.content}</p><div className="ec-actions"><button onClick={()=>onLike(comment)} className={likes.liked[comment.id]?'liked':''}>♥ {likes.counts[comment.id]||0}</button><button onClick={()=>onReply(comment.id)}>↩ Reply</button><button onClick={()=>onCopy(comment)}>{copied===comment.id?'✓ Shared':'↗ Share'}</button>{user&&user.id!==comment.user_id&&<button onClick={()=>onReport(comment)}>⚑ Report</button>}{user?.id===comment.user_id&&<button onClick={()=>onDelete(comment)}>Delete</button>}</div>{replies.length>0&&<div className="ec-replies">{replies.map(reply=><CommentCard key={reply.id} comment={reply} replies={[]} profile={profileFor(reply.user_id)} user={user} likes={likes} onLike={onLike} onReply={onReply} onCopy={onCopy} copied={copied} onReport={onReport} onDelete={onDelete} onProfile={onProfile} onPreview={onPreview} profileFor={profileFor}/>)}</div>}</div></article>}
function ProfilePreview({profile,onClose,onOpen}){return <div className="ec-preview-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="ec-preview"><button className="ec-preview-close" onClick={onClose}>×</button><Avatar profile={profile}/><strong>{profile?.display_name||profile?.username||'Reader'}</strong><span>@{profile?.username||'reader'}</span>{profile?.bio&&<p>{profile.bio}</p>}<button className="ec-preview-open" onClick={onOpen}>View profile</button></section></div>}
