import { useEffect, useMemo, useRef, useState } from 'react';
import { supabase } from './supabase';

const REACTIONS=['❤️','😂','😍','🔥','😭','😮','😎','🤯','🥹','😈','👀','👏','🙌','💀','🤡','🫶','✨','💯','🎉','🙏','😡','🤔','🥰','😴','🦚'];
const COOLDOWN=5000;
const ago=v=>{const m=Math.floor(Math.max(0,Date.now()-new Date(v).getTime())/60000);if(m<1)return'now';if(m<60)return`${m}m`;const h=Math.floor(m/60);if(h<24)return`${h}h`;return`${Math.floor(h/24)}d`};

export default function GroupChat(){
 const [route,setRoute]=useState(location.hash),[user,setUser]=useState(null),[messages,setMessages]=useState([]),[profiles,setProfiles]=useState({}),[reactions,setReactions]=useState({}),[reads,setReads]=useState({}),[text,setText]=useState(''),[loading,setLoading]=useState(true),[sending,setSending]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[picker,setPicker]=useState(null),[cooldown,setCooldown]=useState(0);
 const bottom=useRef(null),press=useRef(null),readObserver=useRef(null);
 useEffect(()=>{const h=()=>setRoute(location.hash);addEventListener('hashchange',h);supabase.auth.getSession().then(({data})=>setUser(data?.session?.user||null));const{data:l}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user||null));return()=>{removeEventListener('hashchange',h);l.subscription.unsubscribe();clearTimeout(press.current)}},[]);
 const load=async()=>{setLoading(true);setError('');const{data:m,error:e}=await supabase.from('group_chat_messages').select('id,user_id,content,created_at').order('created_at',{ascending:true}).limit(100);if(e){setError(e.message);setLoading(false);return}setMessages(m||[]);const ids=[...new Set((m||[]).map(x=>x.user_id))];if(ids.length){const{data:p}=await supabase.from('profiles').select('id,username,display_name,avatar_url').in('id',ids);const map={};for(const x of p||[])map[x.id]=x;setProfiles(map)}const mids=(m||[]).map(x=>x.id);if(mids.length){const[{data:r},{data:rr}]=await Promise.all([supabase.from('group_chat_reactions').select('id,message_id,user_id,reaction').in('message_id',mids),supabase.from('group_chat_reads').select('message_id,user_id').in('message_id',mids)]);const rm={};for(const x of r||[]){if(!rm[x.message_id])rm[x.message_id]=[];rm[x.message_id].push(x)}setReactions(rm);const readm={};for(const x of rr||[]){if(!readm[x.message_id])readm[x.message_id]=new Set();readm[x.message_id].add(x.user_id)}setReads(readm)}setLoading(false)};
 useEffect(()=>{if(route!=='#group-chat')return;load();const channel=supabase.channel('atma-rekha-group-chat');channel.on('postgres_changes',{event:'INSERT',schema:'public',table:'group_chat_messages'},p=>setMessages(x=>x.some(m=>m.id===p.new.id)?x:[...x,p.new].slice(-100)));channel.on('postgres_changes',{event:'INSERT',schema:'public',table:'group_chat_reactions'},p=>setReactions(x=>({...x,[p.new.message_id]:[...(x[p.new.message_id]||[]),p.new]})));channel.on('postgres_changes',{event:'DELETE',schema:'public',table:'group_chat_reactions'},p=>setReactions(x=>({...x,[p.old.message_id]:(x[p.old.message_id]||[]).filter(r=>r.id!==p.old.id)})));channel.on('postgres_changes',{event:'INSERT',schema:'public',table:'group_chat_reads'},p=>setReads(x=>({...x,[p.new.message_id]:new Set([...(x[p.new.message_id]||[]),p.new.user_id])})));channel.subscribe();return()=>{supabase.removeChannel(channel)}},[route]);
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:'smooth'})},[messages.length]);
 useEffect(()=>{if(!cooldown)return;const t=setInterval(()=>setCooldown(v=>Math.max(0,v-100)),100);return()=>clearInterval(t)},[cooldown]);
 const markRead=async id=>{if(!user)return;const seen=reads[id];if(seen?.has(user.id))return;await supabase.from('group_chat_reads').upsert({message_id:id,user_id:user.id},{onConflict:'message_id,user_id'});setReads(x=>({...x,[id]:new Set([...(x[id]||[]),user.id])}))};
 const send=async()=>{if(!user){setNotice('Sign in to chat');return}const content=text.trim();if(!content||sending)return;if(cooldown){setNotice(`${Math.ceil(cooldown/1000)}s`);return}setSending(true);setNotice('');const{error:e}=await supabase.from('group_chat_messages').insert({user_id:user.id,content});if(e)setError(e.message);else{setText('');setCooldown(COOLDOWN)}setSending(false)};
 const toggleReaction=async(id,reaction)=>{if(!user){setNotice('Sign in to react');return}const own=(reactions[id]||[]).find(x=>x.user_id===user.id&&x.reaction===reaction);if(own)await supabase.from('group_chat_reactions').delete().eq('id',own.id);else await supabase.from('group_chat_reactions').insert({message_id:id,user_id:user.id,reaction});setPicker(null)};
 const startHold=id=>{clearTimeout(press.current);press.current=setTimeout(()=>setPicker(id),3000)};const endHold=()=>clearTimeout(press.current);
 const grouped=useMemo(()=>messages.map((m,i)=>({...m,profile:profiles[m.user_id],mine:m.user_id===user?.id,same:m.user_id===messages[i-1]?.user_id&&new Date(m.created_at)-new Date(messages[i-1]?.created_at)<300000})),[messages,profiles,user]);
 useEffect(()=>{if(route!=='#group-chat'||!user)return;readObserver.current?.disconnect();const root=document.querySelector('.group-chat-feed');if(!root)return;const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)markRead(e.target.dataset.message)}),{root,threshold:.65});document.querySelectorAll('.group-message').forEach(el=>obs.observe(el));readObserver.current=obs;return()=>obs.disconnect()},[messages,user,route]);
 if(route!=='#group-chat')return null;
 return <main className="group-chat-page"><section className="group-chat-shell"><header className="group-chat-header"><button type="button" onClick={()=>location.hash='profile'} aria-label="Back">←</button><div className="group-chat-title-mark">✦</div><div><p>ATMA REKHA</p><h1>Community Group</h1><span>Live community chat</span></div><div className="group-chat-status"><i/>LIVE</div></header>{notice&&<div className="group-chat-notice">{notice}</div>}{error&&<div className="group-chat-error">{error}</div>}<div className="group-chat-feed">{loading?<div className="group-chat-loading"><div>✦</div><strong>Entering…</strong></div>:!grouped.length?<div className="group-chat-empty"><div>🌙</div><h2>Say hello.</h2><p>Start the conversation.</p></div>:grouped.map(m=>{const p=m.profile,rs=reactions[m.id]||[],counts={};rs.forEach(r=>counts[r.reaction]=(counts[r.reaction]||0)+1);const readCount=Math.max(0,(reads[m.id]?.size||0)-(m.mine?1:0));return <article key={m.id} data-message={m.id} className={`group-message ${m.mine?'mine':''} ${m.same?'same-user':''}`} onPointerDown={()=>startHold(m.id)} onPointerUp={endHold} onPointerCancel={endHold} onContextMenu={e=>e.preventDefault()}><div className="group-avatar">{p?.avatar_url?<img src={p.avatar_url} alt=""/>:<span>{(p?.display_name||'R').slice(0,1).toUpperCase()}</span>}</div><div className="group-message-main">{!m.same&&<div className="group-message-meta"><strong>{p?.display_name||'Reader'}</strong><span>{ago(m.created_at)}</span></div>}<div className="group-message-row"><div className="group-message-bubble">{m.content}</div><small className="group-read">Read by {readCount}</small></div>{Object.keys(counts).length>0&&<div className="group-reactions">{Object.entries(counts).map(([r,c])=><button key={r} type="button" onClick={()=>toggleReaction(m.id,r)} className={rs.some(x=>x.user_id===user?.id&&x.reaction===r)?'mine':''}>{r} <b>{c}</b></button>)}</div>}</div>{picker===m.id&&<div className="group-reaction-picker" onPointerDown={e=>e.stopPropagation()}><div className="group-reaction-picker-head"><span>React</span><button type="button" onClick={()=>setPicker(null)}>×</button></div><div>{REACTIONS.map(r=><button type="button" key={r} onClick={()=>toggleReaction(m.id,r)}>{r}</button>)}</div></div>}</article>})}<div ref={bottom}/></div><form className="group-composer" onSubmit={e=>{e.preventDefault();send()}}><div className="group-composer-inner"><button type="submit" aria-label="Send" disabled={!user||sending||!text.trim()||cooldown>0}>➤</button><textarea value={text} onChange={e=>setText(e.target.value.slice(0,700))} placeholder={user?'Message…':'Sign in'} maxLength={700} rows={1} disabled={!user||sending}/><span>{text.length}</span></div></form></section></main>;
}

export function GroupChatLauncher({user}){useEffect(()=>{if(!user)return;const mount=()=>{const card=document.querySelector('.profile-v2-card'),community=card?.querySelector('.profile-community-card');if(!card||!community)return false;if(card.querySelector('.profile-group-chat-card'))return true;const button=document.createElement('button');button.type='button';button.className='profile-community-card profile-group-chat-card';button.innerHTML='<span class="profile-community-icon group-chat-launch-icon">💬</span><span><strong>Group Chat</strong><small>Talk with the Atma Rekha community</small></span><b>→</b>';button.addEventListener('click',()=>{location.hash='group-chat'});community.insertAdjacentElement('afterend',button);return true};mount();const o=new MutationObserver(mount);o.observe(document.body,{childList:true,subtree:true});return()=>o.disconnect()},[user]);return null}
