import { useEffect, useMemo, useRef, useState } from 'react';
import { supabase } from './supabase';

const REACTIONS=['❤️','😂','😍','🔥','😭','😮','😎','🤯','🥹','😈','👀','👏','🙌','💀','🤡','🫶','✨','💯','🎉','🙏','😡','🤔','🥰','😴','🦚'];
const MAX_TEXT=700;
const SEND_GAP=5000;
const MESSAGE_LIMIT=100;

const styles=`
.group-chat-page{min-height:100dvh;background:#0b0b0d;color:#f5f5f7;display:flex;justify-content:center}
.group-chat-shell{width:min(760px,100%);height:100dvh;background:#101012;display:flex;flex-direction:column;overflow:hidden}
.group-chat-header{height:52px;min-height:52px;display:flex;align-items:center;gap:9px;padding:0 12px;background:#121214;border-bottom:1px solid rgba(255,255,255,.07);z-index:10}
.group-chat-back{width:32px;height:32px;border:0;border-radius:50%;background:#1b1b1f;color:#eee;font-size:19px;display:grid;place-items:center;cursor:pointer}
.group-chat-title{font-size:14px;font-weight:650}.group-chat-live{margin-left:auto;display:flex;align-items:center;gap:5px;font-size:9px;color:#8e8e96}.group-chat-live i{width:6px;height:6px;border-radius:50%;background:#74d68a}
.group-chat-feed{flex:1;overflow-y:auto;overscroll-behavior:contain;padding:14px 12px 18px;background:#0d0d0f}
.group-message{position:relative;display:flex;align-items:flex-end;gap:7px;max-width:90%;margin:0 0 14px;touch-action:pan-y}
.group-message.mine{margin-left:auto;flex-direction:row-reverse}.group-message.same{margin-top:-6px}
.group-avatar{width:26px;height:26px;min-width:26px;border-radius:50%;overflow:hidden;background:#202024;border:1px solid rgba(255,255,255,.08);display:grid;place-items:center;color:#aaa;font-size:10px}
.group-avatar img{width:100%;height:100%;object-fit:cover}.group-main{min-width:0;max-width:calc(100% - 33px)}
.group-meta{display:flex;gap:6px;align-items:center;margin:0 7px 3px;color:#8d8d96;font-size:10px}.group-meta strong{color:#bdbdc5;font-weight:600}.group-message.mine .group-meta{justify-content:flex-end}
.group-row{display:flex;align-items:flex-end;gap:7px}.group-message.mine .group-row{flex-direction:row-reverse}
.group-bubble{max-width:min(560px,72vw);padding:9px 12px;border-radius:15px 15px 15px 4px;background:#19191d;color:#ededf0;font-size:13px;line-height:1.42;overflow-wrap:anywhere;box-shadow:0 1px 2px #0005;user-select:text}
.group-message.mine .group-bubble{background:#25252a;border-radius:15px 15px 4px 15px;color:#fff}
.group-read{width:27px;min-width:27px;text-align:center;font-size:8px;line-height:1.1;color:#73737c}.group-read b{display:block;margin-top:2px;color:#9a9aa2;font-size:9px}
.group-reactions{display:flex;flex-wrap:wrap;gap:3px;margin:4px 5px 0}.group-reactions button{border:1px solid rgba(255,255,255,.09);background:#18181c;color:#ddd;border-radius:10px;padding:2px 6px;font-size:11px;cursor:pointer}.group-reactions button.mine{background:#29292f;border-color:rgba(255,255,255,.2)}
.group-picker{position:fixed;z-index:100;width:252px;padding:7px;border:1px solid rgba(255,255,255,.1);border-radius:14px;background:#18181c;box-shadow:0 18px 45px #000b;touch-action:manipulation}
.group-picker-top{height:22px;display:flex;align-items:center;justify-content:space-between;color:#999;font-size:10px;padding:0 4px 5px}.group-picker-top button{border:0;background:none;color:#aaa;font-size:18px;cursor:pointer}
.group-picker-grid{display:grid;grid-template-columns:repeat(9,1fr);gap:2px}.group-picker-grid button{border:0;background:transparent;border-radius:8px;padding:5px;font-size:20px;cursor:pointer}.group-picker-grid button:active{background:#29292f}
.group-composer{padding:8px 10px calc(8px + env(safe-area-inset-bottom));background:#121214;border-top:1px solid rgba(255,255,255,.07)}
.group-composer-inner{display:flex;align-items:flex-end;gap:7px;background:#19191d;border:1px solid rgba(255,255,255,.08);border-radius:18px;padding:5px 7px}.group-send{width:32px;height:32px;min-width:32px;border:0;border-radius:50%;background:#eee;color:#111;display:grid;place-items:center;font-size:15px;cursor:pointer}.group-send:disabled{opacity:.3}
.group-input{flex:1;min-height:32px;max-height:110px;resize:none;border:0;outline:0;background:transparent;color:#f4f4f6;font-size:13px;line-height:1.35;padding:7px 2px;font-family:inherit}.group-input::placeholder{color:#707078}.group-count{font-size:8px;color:#606068;padding-bottom:6px}
.group-error,.group-notice{text-align:center;font-size:10px;padding:5px 8px;background:#17171a;color:#aaa}.group-error{color:#e08d8d}
.group-empty{text-align:center;color:#666;padding-top:30vh}.group-empty b{display:block;font-size:13px;color:#888;margin-top:8px;font-weight:500}.group-empty span{font-size:10px;color:#555}
@media(max-width:600px){.group-chat-feed{padding:12px 8px 18px}.group-message{max-width:95%;margin-bottom:15px}.group-bubble{max-width:76vw;font-size:13px}.group-avatar{width:24px;height:24px;min-width:24px}.group-picker{width:238px}.group-picker-grid button{font-size:18px;padding:4px}}
`;

const firstLetter=p=>(p?.display_name||p?.username||'R').trim().slice(0,1).toUpperCase();
const displayName=(p,userId,currentUser)=>p?.display_name||p?.username||(userId===currentUser?.id?'You':'Reader');

export default function GroupChat(){
 const [route,setRoute]=useState(location.hash);const [user,setUser]=useState(null);const [messages,setMessages]=useState([]);const [profiles,setProfiles]=useState({});const [reactions,setReactions]=useState({});const [reads,setReads]=useState({});const [text,setText]=useState('');const [loading,setLoading]=useState(true);const [sending,setSending]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [picker,setPicker]=useState(null);const [cooldown,setCooldown]=useState(0);
 const channelRef=useRef(null);const timerRef=useRef(null);const feedRef=useRef(null);const pressRef=useRef(null);const readObserverRef=useRef(null);const pressTargetRef=useRef(null);const atBottomRef=useRef(true);

 useEffect(()=>{const onHash=()=>setRoute(location.hash);addEventListener('hashchange',onHash);let authSub;supabase.auth.getSession().then(({data})=>setUser(data?.session?.user||null));const auth=supabase.auth.onAuthStateChange((_event,session)=>setUser(session?.user||null));authSub=auth.data?.subscription;return()=>{removeEventListener('hashchange',onHash);authSub?.unsubscribe();clearTimeout(pressRef.current)}},[]);

 const loadProfiles=async ids=>{const unique=[...new Set(ids.filter(Boolean))];if(!unique.length)return;const{data,error:e}=await supabase.from('profiles').select('id,username,display_name,avatar_url').in('id',unique);if(!e&&data?.length)setProfiles(x=>{const n={...x};data.forEach(p=>n[p.id]=p);return n})};
 const load=async()=>{setLoading(true);setError('');const{data:m,error:e}=await supabase.from('group_chat_messages').select('id,user_id,content,created_at').order('created_at',{ascending:true}).limit(MESSAGE_LIMIT);if(e){setError(e.message);setLoading(false);return}const list=m||[];setMessages(list);await loadProfiles(list.map(x=>x.user_id));const ids=list.map(x=>x.id);if(ids.length){const[reactRes,readRes]=await Promise.all([supabase.from('group_chat_reactions').select('id,message_id,user_id,reaction').in('message_id',ids),supabase.from('group_chat_reads').select('message_id,user_id').in('message_id',ids)]);if(reactRes.error)setError(reactRes.error.message);else{const rm={};(reactRes.data||[]).forEach(r=>(rm[r.message_id]??=[]).push(r));setReactions(rm)}if(!readRes.error){const rr={};(readRes.data||[]).forEach(r=>(rr[r.message_id]??=new Set()).add(r.user_id));setReads(rr)}}setLoading(false)};

 const refreshAfterRealtimeIssue=()=>{clearTimeout(timerRef.current);timerRef.current=setTimeout(()=>{if(route==='#group-chat')load()},12000)};
 useEffect(()=>{if(route!=='#group-chat')return;let alive=true;load();const channel=supabase.channel('atma-rekha-group-chat');channelRef.current=channel;
  channel.on('postgres_changes',{event:'INSERT',schema:'public',table:'group_chat_messages'},async payload=>{if(!alive)return;const row=payload.new;if(!row?.id)return;setMessages(x=>x.some(m=>m.id===row.id)?x:[...x,row].slice(-MESSAGE_LIMIT));await loadProfiles([row.user_id]);});
  channel.on('postgres_changes',{event:'INSERT',schema:'public',table:'group_chat_reactions'},payload=>{if(!alive)return;const row=payload.new;if(!row?.id)return;setReactions(x=>{const list=x[row.message_id]||[];if(list.some(r=>r.id===row.id))return x;return {...x,[row.message_id]:[...list,row]}})});
  channel.on('postgres_changes',{event:'DELETE',schema:'public',table:'group_chat_reactions'},payload=>{if(!alive)return;const row=payload.old;if(!row?.id)return;setReactions(x=>({...x,[row.message_id]:(x[row.message_id]||[]).filter(r=>r.id!==row.id)}))});
  channel.on('postgres_changes',{event:'INSERT',schema:'public',table:'group_chat_reads'},payload=>{if(!alive)return;const row=payload.new;if(!row?.message_id||!row?.user_id)return;setReads(x=>({...x,[row.message_id]:new Set([...(x[row.message_id]||[]),row.user_id])}))});
  channel.subscribe(status=>{if(status==='SUBSCRIBED')clearTimeout(timerRef.current);else refreshAfterRealtimeIssue()});
  return()=>{alive=false;clearTimeout(timerRef.current);if(channelRef.current)supabase.removeChannel(channelRef.current);channelRef.current=null}},[route]);

 useEffect(()=>{const feed=feedRef.current;if(!feed)return;const onScroll=()=>{atBottomRef.current=feed.scrollHeight-feed.scrollTop-feed.clientHeight<100};feed.addEventListener('scroll',onScroll);onScroll();return()=>feed.removeEventListener('scroll',onScroll)},[]);
 useEffect(()=>{if(!feedRef.current)return;if(atBottomRef.current)feedRef.current.scrollTo({top:feedRef.current.scrollHeight,behavior:'smooth'})},[messages.length]);
 useEffect(()=>{if(!cooldown)return;const t=setInterval(()=>setCooldown(v=>Math.max(0,v-100)),100);return()=>clearInterval(t)},[cooldown]);

 const markRead=async id=>{if(!user||reads[id]?.has(user.id))return;const{error:e}=await supabase.from('group_chat_reads').upsert({message_id:id,user_id:user.id},{onConflict:'message_id,user_id'});if(!e)setReads(x=>({...x,[id]:new Set([...(x[id]||[]),user.id])}))};
 useEffect(()=>{if(route!=='#group-chat'||!user||!feedRef.current)return;readObserverRef.current?.disconnect();const obs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)markRead(e.target.dataset.message)}),{root:feedRef.current,threshold:.65});feedRef.current.querySelectorAll('[data-message]').forEach(el=>obs.observe(el));readObserverRef.current=obs;return()=>obs.disconnect()},[messages,user,route]);

 const send=async()=>{if(!user){setNotice('Sign in to chat');return}const content=text.trim();if(!content||sending)return;if(cooldown){setNotice(`${Math.ceil(cooldown/1000)}s`);return}setSending(true);setError('');setNotice('');const{data:row,error:e}=await supabase.from('group_chat_messages').insert({user_id:user.id,content}).select('id,user_id,content,created_at').single();if(e){setError(e.message);setSending(false);return}setText('');setCooldown(SEND_GAP);setMessages(x=>x.some(m=>m.id===row.id)?x:[...x,row].slice(-MESSAGE_LIMIT));setProfiles(x=>x[user.id]?x:{...x,[user.id]:{id:user.id,display_name:user.user_metadata?.display_name||user.user_metadata?.name||'You',username:user.user_metadata?.username||'',avatar_url:user.user_metadata?.avatar_url||null}});requestAnimationFrame(()=>feedRef.current?.scrollTo({top:feedRef.current.scrollHeight,behavior:'smooth'}));setSending(false)};

 const toggleReaction=async(messageId,reaction)=>{if(!user){setNotice('Sign in to react');return}const current=reactions[messageId]||[];const own=current.find(r=>r.user_id===user.id&&r.reaction===reaction);if(own){setReactions(x=>({...x,[messageId]:(x[messageId]||[]).filter(r=>r.id!==own.id)}));const{error:e}=await supabase.from('group_chat_reactions').delete().eq('id',own.id);if(e){setError(e.message);setReactions(x=>({...x,[messageId]:[...(x[messageId]||[]),own]}))}}else{const temp=`temp-${Date.now()}-${Math.random()}`;const optimistic={id:temp,message_id:messageId,user_id:user.id,reaction};setReactions(x=>({...x,[messageId]:[...(x[messageId]||[]),optimistic]}));const{data:row,error:e}=await supabase.from('group_chat_reactions').insert({message_id:messageId,user_id:user.id,reaction}).select('id,message_id,user_id,reaction').single();if(e){setError(e.message);setReactions(x=>({...x,[messageId]:(x[messageId]||[]).filter(r=>r.id!==temp)}))}else setReactions(x=>({...x,[messageId]:(x[messageId]||[]).map(r=>r.id===temp?row:r)}))}setPicker(null)};

 const openPicker=id=>{const el=document.querySelector(`[data-message="${id}"]`);if(!el)return;const r=el.getBoundingClientRect();const top=Math.max(8,Math.min(window.innerHeight-230,r.top-205));const left=Math.max(8,Math.min(window.innerWidth-260,r.left));setPicker({id,top,left})};
 const beginHold=(e,id)=>{if(e.target.closest('.group-picker,.group-reactions,.group-read'))return;clearTimeout(pressRef.current);pressTargetRef.current=id;pressRef.current=setTimeout(()=>{if(pressTargetRef.current===id)openPicker(id)},3000)};
 const cancelHold=()=>{clearTimeout(pressRef.current);pressRef.current=null;pressTargetRef.current=null};

 const grouped=useMemo(()=>messages.map((m,i)=>({...m,profile:profiles[m.user_id],mine:m.user_id===user?.id,same:i>0&&m.user_id===messages[i-1].user_id&&new Date(m.created_at)-new Date(messages[i-1].created_at)<300000})),[messages,profiles,user]);
 const time=v=>{const d=new Date(v),n=Date.now(),mins=Math.floor((n-d.getTime())/60000);if(mins<1)return'now';if(mins<60)return`${mins}m`;const h=Math.floor(mins/60);if(h<24)return`${h}h`;return`${Math.floor(h/24)}d`};
 if(route!=='#group-chat')return null;
 return <><style>{styles}</style><main className="group-chat-page"><section className="group-chat-shell"><header className="group-chat-header"><button className="group-chat-back" type="button" onClick={()=>{cancelHold();location.hash='profile'}} aria-label="Back">←</button><span className="group-chat-title">💬 Group Chat</span><span className="group-chat-live"><i/>LIVE</span></header>{notice&&<div className="group-notice">{notice}</div>}{error&&<div className="group-error">{error}</div>}<div className="group-chat-feed" ref={feedRef}>{loading?<div className="group-empty"><b>Loading…</b></div>:grouped.length===0?<div className="group-empty"><b>No messages yet</b><span>Start the conversation.</span></div>:grouped.map(m=>{const p=m.profile,rs=reactions[m.id]||[],counts={};rs.forEach(r=>counts[r.reaction]=(counts[r.reaction]||0)+1);const readCount=Math.max(0,(reads[m.id]?.size||0)-(m.mine?1:0));return <article key={m.id} data-message={m.id} className={`group-message ${m.mine?'mine':''} ${m.same?'same':''}`} onPointerDown={e=>beginHold(e,m.id)} onPointerUp={cancelHold} onPointerCancel={cancelHold} onPointerLeave={cancelHold} onContextMenu={e=>e.preventDefault()}><div className="group-avatar">{p?.avatar_url?<img src={p.avatar_url} alt=""/>:<span>{firstLetter(p)}</span>}</div><div className="group-main">{!m.same&&<div className="group-meta"><strong>{displayName(p,m.user_id,user)}</strong><span>{time(m.created_at)}</span></div>}<div className="group-row"><div className="group-bubble">{m.content}</div><small className="group-read">Read<b>{readCount}</b></small></div>{Object.keys(counts).length>0&&<div className="group-reactions">{Object.entries(counts).map(([r,c])=><button type="button" key={r} className={rs.some(x=>x.user_id===user?.id&&x.reaction===r)?'mine':''} onPointerDown={e=>e.stopPropagation()} onClick={()=>toggleReaction(m.id,r)}>{r} {c}</button>)}</div>}</div></article>})}</div><form className="group-composer" onSubmit={e=>{e.preventDefault();send()}}><div className="group-composer-inner"><button className="group-send" type="submit" aria-label="Send" disabled={!user||sending||!text.trim()||cooldown>0}>➤</button><textarea className="group-input" value={text} onChange={e=>setText(e.target.value.slice(0,MAX_TEXT))} placeholder={user?'Message…':'Sign in'} disabled={!user||sending} maxLength={MAX_TEXT} rows={1}/><span className="group-count">{text.length}</span></div></form></section>{picker&&<div className="group-picker" style={{top:picker.top,left:picker.left}} onPointerDown={e=>e.stopPropagation()}><div className="group-picker-top"><span>React</span><button type="button" onClick={()=>setPicker(null)}>×</button></div><div className="group-picker-grid">{REACTIONS.map(r=><button type="button" key={r} onClick={()=>toggleReaction(picker.id,r)}>{r}</button>)}</div></div>}</main></>;
}

export function GroupChatLauncher({user}){useEffect(()=>{if(!user)return;const mount=()=>{const card=document.querySelector('.profile-v2-card'),community=card?.querySelector('.profile-community-card');if(!card||!community)return false;if(card.querySelector('.profile-group-chat-card'))return true;const button=document.createElement('button');button.type='button';button.className='profile-community-card profile-group-chat-card';button.innerHTML='<span class="profile-community-icon group-chat-launch-icon">💬</span><span><strong>Group Chat</strong><small>Chat with the community</small></span><b>→</b>';button.addEventListener('click',()=>{location.hash='group-chat'});community.insertAdjacentElement('afterend',button);return true};mount();const observer=new MutationObserver(mount);observer.observe(document.body,{childList:true,subtree:true});return()=>observer.disconnect()},[user]);return null}
