import { useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import { supabase } from './supabase';

const PLANS = [
  { id: 'free', icon: '🆓', name: 'Free Member', amount: 0, eyebrow: 'FREE', description: 'Start reading Atma Rekha.', features: ['Chapters 1–5 forever free', 'Bookmarks & reading history', 'Ratings, comments & notifications'] },
  { id: 'mini_member', icon: '🧸', name: 'Mini Member', amount: 29, eyebrow: 'SUPPORT', description: 'Keep reading and support the manga.', features: ['All chapters', '🧸 Mini Member badge', 'Support future chapters'] },
  { id: 'supporter', icon: '🌸', name: 'Member', amount: 49, eyebrow: 'POPULAR', popular: true, description: 'Read all chapters and support Atma Rekha.', features: ['All chapters', '🌸 Member badge', 'Member recognition', 'Support future chapters'] },
  { id: 'premium', icon: '🦚', name: 'Premium Member', amount: 99, eyebrow: 'PREMIUM', description: 'Get the full experience and extra recognition.', features: ['All chapters', '🦚 Premium Member badge', 'Priority comment placement', 'Premium recognition'] },
];
function routeNow() { return window.location.hash.replace(/^#/, '') || 'home'; }
function formatDate(value) { return value ? new Date(value).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }) : '—'; }
async function getFunctionError(error, fallback) { if (!error) return fallback; try { const response = error.context; if (response && typeof response.json === 'function') { const body = await response.clone().json(); if (body?.error) return [body.error, body.reason].filter(Boolean).join(' · ') || fallback; } } catch {} return error.message || fallback; }
async function authHeaders() { const { data, error } = await supabase.auth.getSession(); if (error || !data?.session?.access_token) throw new Error('Your session has expired. Please sign in again.'); return { Authorization: `Bearer ${data.session.access_token}` }; }

export default function Membership() {
  const [route, setRoute] = useState(routeNow()); const [user, setUser] = useState(null); const [subscription, setSubscription] = useState(null); const [loading, setLoading] = useState(false); const [cancelling, setCancelling] = useState(false); const [selected, setSelected] = useState(null); const [flowOpen, setFlowOpen] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const loadSubscription = async currentUser => { if (!currentUser) { setSubscription(null); return; } const { data, error } = await supabase.from('user_subscriptions').select('plan_id,status,current_period_start,current_period_end,cancel_at_period_end,provider_subscription_id').eq('user_id', currentUser.id).order('created_at', { ascending: false }).limit(20); if (error) { setSubscription(null); return; } const rows = data || []; const now = Date.now(); const activeRow = rows.find(row => row.status === 'active' || (row.status === 'cancelled' && row.current_period_end && new Date(row.current_period_end).getTime() > now)); setSubscription(activeRow || rows.find(row => row.status === 'pending') || null); };
  useEffect(() => { const onHash = () => setRoute(routeNow()); window.addEventListener('hashchange', onHash); const load = async () => { const { data } = await supabase.auth.getSession(); const current = data?.session?.user || null; setUser(current); await loadSubscription(current); }; load(); const { data: listener } = supabase.auth.onAuthStateChange((_event, session) => { const current = session?.user || null; setUser(current); loadSubscription(current); }); return () => { window.removeEventListener('hashchange', onHash); listener.subscription.unsubscribe(); }; }, []);
  const beginCheckout = async plan => {
    if (!user) { window.dispatchEvent(new CustomEvent('atma-open-auth', { detail: { mode: 'login', returnTo: 'membership' } })); return; }
    setError(''); setMessage(''); setLoading(true); setFlowOpen(false);
    try {
      const headers = await authHeaders();
      const { data, error: invokeError } = await supabase.functions.invoke('create-razorpay-subscription', { body: { plan_id: plan.id }, headers });
      if (invokeError) throw new Error(await getFunctionError(invokeError, 'Unable to create the Razorpay subscription.'));
      if (!data?.subscription_id || !data?.key_id) throw new Error(data?.error || 'Unable to start membership checkout.');
      if (!window.Razorpay) throw new Error('Razorpay Checkout could not be loaded. Please refresh and try again.');
      const checkout = new window.Razorpay({ key: data.key_id, subscription_id: data.subscription_id, name: 'Atma Rekha', description: `${plan.name} · ₹${plan.amount}/month`, image: `${window.location.origin}/ishani.png`, prefill: { email: user.email || '' }, notes: { plan_id: plan.id }, theme: { color: '#d946ef' }, modal: { confirm_close: true, escape: true, backdropclose: false, ondismiss: () => setLoading(false), }, handler: async response => {
        try { const verifyHeaders = await authHeaders(); const { data: verification, error: verificationError } = await supabase.functions.invoke('verify-razorpay-subscription', { body: { razorpay_payment_id: response.razorpay_payment_id, razorpay_subscription_id: response.razorpay_subscription_id, razorpay_signature: response.razorpay_signature }, headers: verifyHeaders }); if (verificationError) throw new Error(await getFunctionError(verificationError, 'Unable to verify the membership.')); if (!verification?.success) throw new Error(verification?.error || 'Membership verification failed.'); setMessage('Membership activated.'); await loadSubscription(user); }
        catch (err) { setError(err?.message || 'Unable to verify membership.'); } finally { setLoading(false); }
      } });
      checkout.on('payment.failed', response => { setError(response?.error?.description || 'Membership authorization failed.'); setLoading(false); });
      checkout.open();
    } catch (err) { setError(err?.message || 'Unable to start membership.'); setLoading(false); }
  };
  const choosePaidPlan = plan => { setError(''); setMessage(''); setSelected(plan); if (!user) { window.dispatchEvent(new CustomEvent('atma-open-auth', { detail: { mode: 'login', returnTo: 'membership' } })); return; } setFlowOpen(true); };
  const cancelMembership = async () => {
    if (!subscription?.provider_subscription_id) { setError('Your subscription reference is unavailable. Please contact Atma Rekha support.'); return; }
    if (!window.confirm('Cancel future renewals? Your current membership stays active until the current period ends.')) return;
    setCancelling(true); setError(''); setMessage('');
    try { const headers = await authHeaders(); const { data, error: invokeError } = await supabase.functions.invoke('cancel-razorpay-subscription', { body: { subscription_id: subscription.provider_subscription_id }, headers }); if (invokeError) throw new Error(await getFunctionError(invokeError, 'Unable to cancel the membership.')); if (!data?.ok) throw new Error(data?.error || 'Unable to cancel the membership.'); setMessage('Cancellation scheduled.'); await loadSubscription(user); }
    catch (err) { setError(err?.message || 'Unable to cancel membership.'); } finally { setCancelling(false); }
  };
  if (!route.startsWith('membership')) return <MembershipLauncher user={user} />;
  const periodActive = Boolean(subscription?.current_period_end) && new Date(subscription.current_period_end).getTime() > Date.now();
  const active = Boolean(subscription) && periodActive && (subscription.status === 'active' || subscription.status === 'cancelled');
  const currentPlan = PLANS.find(plan => plan.id === subscription?.plan_id);
  return createPortal(<><div className="membership-overlay" role="dialog" aria-modal="true" aria-label="Atma Rekha membership"><div className="membership-backdrop" onMouseDown={event => { if (event.target === event.currentTarget) window.location.hash = 'profile'; }} /><section className="membership-sheet"><header className="membership-head"><button type="button" className="membership-close" onClick={() => window.location.hash = 'profile'} aria-label="Close membership">×</button><div><p className="membership-kicker">ATMA REKHA</p><h1>Choose your membership.</h1><p>Chapters 1–5 are free forever. Membership starts from Chapter 6.</p></div></header>{active && <div className="membership-active"><span className="membership-active-icon">✓</span><div><strong>{currentPlan?.icon} {currentPlan?.name || 'Member'}</strong><small>Active · {subscription.cancel_at_period_end ? `Access until ${formatDate(subscription.current_period_end)}` : `Next renewal ${formatDate(subscription.current_period_end)}`}</small></div>{!subscription.cancel_at_period_end && <button type="button" onClick={cancelMembership} disabled={cancelling}>{cancelling ? 'Cancelling…' : 'Cancel renewal'}</button>}{subscription.cancel_at_period_end && <em>Cancellation scheduled</em>}</div>}<div className="membership-banners" aria-label="Membership plans">{PLANS.map(plan => <PlanCard key={plan.id} plan={plan} current={plan.id === 'free' ? !active : active && subscription.plan_id === plan.id} busy={loading && selected?.id === plan.id} onChoose={() => plan.id === 'free' ? (window.location.hash = 'home') : choosePaidPlan(plan)} />)}</div><div className="membership-banner-hint"><span>Swipe</span><span>01 / 04</span></div><div className="membership-free-note"><strong>Five chapters. Always free.</strong><span>Chapters 1–5 never require membership.</span></div>{message && <p className="membership-success">✓ {message}</p>}{error && <p className="membership-error">{error}</p>}<p className="membership-legal">Approve the UPI AutoPay mandate in Razorpay. Monthly renewals are automatic.</p></section></div>{flowOpen && selected && <UpiFlowModal plan={selected} loading={loading} onClose={() => setFlowOpen(false)} onChoose={() => beginCheckout(selected)} />}</>, document.body);
}
function PlanCard({ plan, current, busy, onChoose }) { return <article className={`membership-plan ${plan.popular ? 'is-popular' : ''} ${current ? 'is-current' : ''}`}><div className="membership-plan-top"><div className="membership-plan-icon">{plan.icon}</div><p>{plan.eyebrow}</p></div>{plan.popular && <span className="membership-popular">POPULAR</span>}<h2>{plan.name}</h2><p className="membership-price">₹{plan.amount}<small>{plan.amount ? ' / month' : ''}</small></p><p className="membership-description">{plan.description}</p><ul>{plan.features.map(feature => <li key={feature}>✓ {feature}</li>)}</ul><button type="button" className={`membership-button ${current ? 'current' : ''}`} disabled={current || busy} onClick={onChoose}>{current ? 'Current plan' : busy ? 'Opening…' : plan.amount ? `Subscribe · ₹${plan.amount}/month` : 'Read Chapters 1–5'}</button></article>; }
function MembershipLauncher({ user }) { const [ready, setReady] = useState(false); useEffect(() => { if (!user) return undefined; const mount = () => { const card = document.querySelector('.profile-v2-card'); const community = card?.querySelector('.profile-community-card'); if (!card || !community) return false; let slot = card.querySelector('.profile-membership-slot'); if (!slot) { slot = document.createElement('div'); slot.className = 'profile-membership-slot'; community.insertAdjacentElement('afterend', slot); } setReady(true); return true; }; mount(); const observer = new MutationObserver(mount); observer.observe(document.body, { childList: true, subtree: true }); return () => observer.disconnect(); }, [user]); if (!ready) return null; const slot = document.querySelector('.profile-membership-slot'); if (!slot) return null; return createPortal(<button type="button" className="profile-membership-launcher" onClick={() => window.location.hash = 'membership'}><span className="profile-membership-launcher-icon">✦</span><span><strong>Membership</strong><small>Choose a plan</small></span><b>→</b></button>, slot); }
function UpiFlowModal({ plan, loading, onClose, onChoose }) { return createPortal(<div className="membership-phone-overlay" role="dialog" aria-modal="true" aria-label="Razorpay UPI AutoPay"><div className="membership-phone-backdrop" onMouseDown={event => { if (event.target === event.currentTarget) onClose(); }} /><section className="membership-phone-modal membership-upi-modal"><button className="membership-phone-close" type="button" onClick={onClose} aria-label="Close">×</button><div className="membership-phone-mark">{plan.icon}</div><p className="membership-phone-kicker">{plan.name.toUpperCase()} · ₹{plan.amount}/MONTH</p><h2>Continue with UPI AutoPay.</h2><p>Razorpay will show the UPI options available for your account.</p><button type="button" className="membership-button" disabled={loading} onClick={onChoose}>{loading ? 'Opening Razorpay…' : 'Continue to Razorpay'}</button><small className="membership-upi-note">Approve the monthly mandate securely in Razorpay.</small></section></div>, document.body); }
