import { useEffect, useMemo, useState } from 'react';
import { supabase, getCurrentMembership } from './supabase';
import SubscriberBadge from './SubscriberBadge.jsx';

const AVATARS = Array.from({ length: 10 }, (_, i) => `/avatars/avatar-${String(i + 1).padStart(2, '0')}.svg`);
function routeNow() { return window.location.hash.replace(/^#/, '') || 'home'; }
const relativeTime = value => { const d=Math.max(0,Date.now()-new Date(value).getTime()); const m=Math.floor(d/60000); if(m<1)return 'just now'; if(m<60)return `${m}m`; const h=Math.floor(m/60); if(h<24)return `${h}h`; const days=Math.floor(h/24); if(days<30)return `${days}d`; return new Date(value).toLocaleDateString('en-IN',{day:'numeric',month:'short'}); };

export default function ProfileV2() {
  const [route,setRoute]=useState(routeNow),[user,setUser]=useState(null),[profile,setProfile]=useState(null),[editing,setEditing]=useState(false),[avatarPicker,setAvatarPicker]=useState(false);
  const [displayName,setDisplayName]=useState(''),[username,setUsername]=useState(''),[bio,setBio]=useState(''),[email,setEmail]=useState(''),[avatar,setAvatar]=useState(AVATARS[0]);
  const [saving,setSaving]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[tab,setTab]=useState(()=>localStorage.getItem('atma-profile-tab')||'history'),[membershipPlan,setMembershipPlan]=useState(null);
  const [history,setHistory]=useState([]),[bookmarks,setBookmarks]=useState([]),[ratings,setRatings]=useState([]),[comments,setComments]=useState([]);
  const load=async currentUser=>{if(!currentUser)return;setUser(currentUser);setEmail(currentUser.email||'');const {data}=await supabase.from('profiles').select('*').eq('id',currentUser.id).maybeSingle();const next=data||{};setProfile(next);setDisplayName(next.display_name||currentUser.user_metadata?.full_name||'Reader');setUsername(next.username||'');setBio(next.bio||'');setAvatar(next.avatar_url||AVATARS[0]);try{setMembershipPlan(await getCurrentMembership(currentUser.id))}catch(e){console.warn('Membership lookup failed:',e);setMembershipPlan(null)}const [h,b,r,c]=await Promise.all([supabase.from('reading_history').select('chapter_id,page_number,updated_at,chapters(id,chapter_number,title,cover_url,status)').eq('user_id',currentUser.id).order('updated_at',{ascending:false}).limit(50),supabase.from('bookmarks').select('id,chapter_id,created_at,chapters(id,chapter_number,title,cover_url,status)').eq('user_id',currentUser.id).order('created_at',{ascending:false}).limit(50),supabase.from('chapter_ratings').select('id,chapter_id,rating,created_at,chapters(id,chapter_number,title,cover_url,status)').eq('user_id',currentUser.id).order('created_at',{ascending:false}).limit(50),supabase.from('comments').select('id,content,created_at,chapter_id').eq('user_id',currentUser.id).order('created_at',{ascending:false}).limit(50)]);setHistory(h.data||[]);setBookmarks(b.data||[]);setRatings(r.data||[]);setComments(c.data||[]);};
  useEffect(()=>{const onHash=()=>setRoute(routeNow);window.addEventListener('hashchange',onHash);supabase.auth.getSession().then(({data})=>{if(data?.session?.user)load(data.session.user)});const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>{if(s?.user)load(s.user);else{setUser(null);setMembershipPlan(null)}});return()=>{window.removeEventListener('hashchange',onHash);l.subscription.unsubscribe()};},[]);
  const save=async e=>{e.preventDefault();if(!user||saving)return;setSaving(true);setError('');setMessage('');const clean=username.trim().toLowerCase().replace(/[^a-z0-9_]/g,'').slice(0,24);const updates={username:clean||null,display_name:displayName.trim().slice(0,60)||'Reader',bio:bio.trim().slice(0,240)||null,avatar_url:avatar||AVATARS[0]};const {data,error}=await supabase.from('profiles').update(updates).eq('id',user.id).select().single();if(error){setError(error.code==='23505'?'That username is already taken.':error.message);setSaving(false);return}if(email.trim()&&email.trim()!==(user.email||'')){const {error:ee}=await supabase.auth.updateUser({email:email.trim()});if(ee){setError(ee.message);setSaving(false);return}}setProfile(data);setEditing(false);setAvatarPicker(false);setMessage('Profile saved.');setSaving(false)};
  const signOut=async()=>{await supabase.auth.signOut();window.location.hash='home';};
  const list=useMemo(()=>tab==='history'?history:tab==='bookmarks'?bookmarks:tab==='ratings'?ratings:comments,[tab,history,bookmarks,ratings,comments]);
  const display=profile?.display_name||displayName||'Reader';const joinedDate=profile?.created_at?new Date(profile.created_at).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'Recently';
  if(route!=='profile'||!user)return null;
  return <main className="profile-v2-overlay"><div className="profile-v2-shell"><div className="profile-v2-top"><button type="button" onClick={()=>window.location.hash='home'} aria-label="Back">←</button></div><section className="profile-v2-card">
    <div className="profile-v2-header"><div className="profile-v2-avatar-wrap"><img src={avatar||AVATARS[0]} alt="Profile avatar"/>{editing&&<button type="button" className="profile-v2-pencil" onClick={()=>setAvatarPicker(v=>!v)}>✎</button>}{editing&&avatarPicker&&<div className="profile-v2-avatar-picker"><div className="profile-v2-picker-title"><strong>Choose your profile picture</strong><button type="button" onClick={()=>setAvatarPicker(false)}>×</button></div><div className="profile-v2-avatar-grid">{AVATARS.map(src=><button type="button" key={src} className={avatar===src?'selected':''} onClick={()=>{setAvatar(src);setAvatarPicker(false)}}><img src={src} alt=""/></button>)}</div></div>}</div><div className="profile-v2-heading"><p className="section-eyebrow">PROFILE</p><h1>{display}<SubscriberBadge planId={membershipPlan}/></h1><p>@{profile?.username||'set-your-username'}</p><small>Joined {joinedDate}</small></div>{!editing&&<button type="button" className="profile-v2-edit-button" onClick={()=>{setError('');setMessage('');setEditing(true)}}>Edit Profile</button>}</div>
    {editing?<form className="profile-v2-edit-form" onSubmit={save}><label>Display name<input value={displayName} onChange={e=>setDisplayName(e.target.value)} maxLength={60} required/></label><label>Username<input value={username} onChange={e=>setUsername(e.target.value)} placeholder="your_handle" maxLength={24}/></label><label>Email / Gmail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/></label><label>Bio<textarea value={bio} onChange={e=>setBio(e.target.value)} placeholder="Tell readers a little about yourself" maxLength={240} rows="3"/></label><div className="profile-v2-edit-actions"><button type="button" onClick={()=>{setEditing(false);setAvatarPicker(false);load(user)}}>Cancel</button><button className="primary-button" type="submit" disabled={saving}>{saving?'Saving…':'Save Changes'}</button></div>{error&&<p className="profile-v2-error">{error}</p>}{message&&<p className="profile-v2-message">{message}</p>}</form>:<div className="profile-v2-bio">{profile?.bio?<p>{profile.bio}</p>:<p className="muted">Add a short bio so your profile feels like yours.</p>}</div>}
    {!editing&&<><div className="profile-v2-stats"><div><strong>{history.length}</strong><span>Chapters read</span></div><div><strong>{bookmarks.length}</strong><span>Favourites</span></div><div><strong>{ratings.length}</strong><span>Ratings</span></div></div><div className="profile-v2-tabs">{[['history','Reading History'],['bookmarks','Favourites'],['ratings','My Ratings'],['comments','My Comments']].map(([id,label])=><button type="button" key={id} className={tab===id?'active':''} onClick={()=>{setTab(id);localStorage.setItem('atma-profile-tab',id)}}>{label}</button>)}</div><div className="profile-v2-list">{!list.length?<div className="profile-v2-empty"><h3>{tab==='history'?'No reading history yet':tab==='bookmarks'?'No favourites yet':tab==='ratings'?'No ratings yet':'No comments yet'}</h3><p>{tab==='comments'?'Share your thoughts while reading and they will appear here.':'Start reading Atma Rekha and your activity will appear here.'}</p></div>:list.map(row=>{const chapter=row.chapters;return tab==='comments'?<button type="button" key={row.id} className="profile-v2-comment-item" onClick={()=>row.chapter_id&&(window.location.hash=`read-chapter/${encodeURIComponent(row.chapter_id)}`)}><div><strong>{row.content}</strong><small>{relativeTime(row.created_at)}</small></div><b>Open →</b></button>:!chapter?null:<button type="button" key={row.id||row.chapter_id} className="profile-v2-list-item" onClick={()=>window.location.hash=`read-chapter/${encodeURIComponent(chapter.id)}`}><div>{chapter.cover_url?<img src={chapter.cover_url} alt=""/>:<span>AR</span>}<div><small>CHAPTER {chapter.chapter_number}</small><strong>{chapter.title}</strong></div></div><b>{tab==='ratings'?`${row.rating}/10 ★`:tab==='history'?`Page ${row.page_number||1} →`:'Read →'}</b></button>})}</div><button type="button" className="profile-community-card" onClick={()=>window.location.hash='community'}><span className="profile-community-icon">🤝</span><span><strong>Community</strong><small>Creator updates and messages</small></span><b>→</b></button><button type="button" className="profile-signout" onClick={signOut}>Sign out</button></>}
  </section></div></main>;
}
