import { useEffect, useMemo, useState } from 'react';
import { supabase } from './supabase';

const AVATARS = Array.from({ length: 10 }, (_, i) => `/avatars/avatar-${String(i + 1).padStart(2, '0')}.svg`);
const MEMBER_CONTENT = [
  ['characters', 'Character Profiles', 'Meet the characters and explore their stories.'],
  ['power', 'Power-System Explanations', 'Understand the rules and abilities behind Atma Rekha.'],
  ['qa', 'Monthly Q&A', 'Questions and answers from the creator.'],
  ['diary', 'Development Diary', 'Follow the making of Atma Rekha.'],
  ['sketches', 'Character Sketch Vault', 'Early sketches and character exploration.'],
  ['rejected', 'Rejected Artwork Gallery', 'Artwork that changed or never made the final cut.'],
  ['before-after', 'Before → After Artwork', 'See how artwork evolves from draft to final.'],
  ['weapons', 'Weapon Design Archive', 'Explore the designs behind Atma Rekha weapons.'],
  ['illustration', 'Monthly Member Illustration', 'Exclusive monthly artwork for supporters.']
];
function routeNow() { return window.location.hash.replace(/^#/, '') || 'home'; }
const relativeTime = value => { const d=Math.max(0,Date.now()-new Date(value).getTime()); const m=Math.floor(d/60000); if(m<1)return 'just now'; if(m<60)return `${m}m`; const h=Math.floor(m/60); if(h<24)return `${h}h`; const days=Math.floor(h/24); if(days<30)return `${days}d`; return new Date(value).toLocaleDateString('en-IN',{day:'numeric',month:'short'}); };

export default function ProfileV2() {
  const [route,setRoute]=useState(routeNow),[user,setUser]=useState(null),[profile,setProfile]=useState(null),[editing,setEditing]=useState(false),[avatarPicker,setAvatarPicker]=useState(false),[memberContent,setMemberContent]=useState(false),[memberSection,setMemberSection]=useState(null);
  const [displayName,setDisplayName]=useState(''),[username,setUsername]=useState(''),[bio,setBio]=useState(''),[email,setEmail]=useState(''),[avatar,setAvatar]=useState(AVATARS[0]);
  const [saving,setSaving]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[tab,setTab]=useState(()=>localStorage.getItem('atma-profile-tab')||'history');
  const [history,setHistory]=useState([]),[chaptersRead,setChaptersRead]=useState(0),[bookmarks,setBookmarks]=useState([]),[ratings,setRatings]=useState([]),[comments,setComments]=useState([]);
  const load=async currentUser=>{if(!currentUser)return;setUser(currentUser);setEmail(currentUser.email||'');const {data}=await supabase.from('profiles').select('*').eq('id',currentUser.id).maybeSingle();const next=data||{};setProfile(next);setDisplayName(next.display_name||currentUser.user_metadata?.full_name||'Reader');setUsername(next.username||'');setBio(next.bio||'');setAvatar(next.avatar_url||AVATARS[0]);const [h,count,b,r,c]=await Promise.all([supabase.from('reading_history').select('chapter_id,page_number,updated_at,chapters(id,chapter_number,title,cover_url,status)').eq('user_id',currentUser.id).order('updated_at',{ascending:false}).limit(1),supabase.from('reading_history').select('chapter_id',{count:'exact',head:true}).eq('user_id',currentUser.id),supabase.from('bookmarks').select('id,chapter_id,created_at,chapters(id,chapter_number,title,cover_url,status)').eq('user_id',currentUser.id).order('created_at',{ascending:false}).limit(50),supabase.from('chapter_ratings').select('id,chapter_id,rating,created_at,chapters(id,chapter_number,title,cover_url,status)').eq('user_id',currentUser.id).order('created_at',{ascending:false}).limit(50),supabase.from('comments').select('id,content,created_at,chapter_id').eq('user_id',currentUser.id).order('created_at',{ascending:false}).limit(50)]);setHistory(h.data||[]);setChaptersRead(count.count||0);setBookmarks(b.data||[]);setRatings(r.data||[]);setComments(c.data||[]);};
  useEffect(()=>{const onHash=()=>setRoute(routeNow);window.addEventListener('hashchange',onHash);supabase.auth.getSession().then(({data})=>{if(data?.session?.user)load(data.session.user)});const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>{if(s?.user)load(s.user);else setUser(null)});return()=>{window.removeEventListener('hashchange',onHash);l.subscription.unsubscribe()};},[]);
  const save=async e=>{e.preventDefault();if(!user||saving)return;setSaving(true);setError('');setMessage('');const clean=username.trim().toLowerCase().replace(/[^a-z0-9_]/g,'').slice(0,24);const updates={username:clean||null,display_name:displayName.trim().slice(0,60)||'Reader',bio:bio.trim().slice(0,240)||null,avatar_url:avatar||AVATARS[0]};const {data,error}=await supabase.from('profiles').update(updates).eq('id',user.id).select().single();if(error){setError(error.code==='23505'?'That username is already taken.':error.message);setSaving(false);return}if(email.trim()&&email.trim()!==(user.email||'')){const {error:ee}=await supabase.auth.updateUser({email:email.trim()});if(ee){setError(ee.message);setSaving(false);return}}setProfile(data);setEditing(false);setAvatarPicker(false);setMessage('Profile saved.');setSaving(false)};
  const signOut=async()=>{await supabase.auth.signOut();window.location.hash='home';};
  const list=useMemo(()=>tab==='history'?history:tab==='bookmarks'?bookmarks:tab==='ratings'?ratings:comments,[tab,history,bookmarks,ratings,comments]);
  const display=profile?.display_name||displayName||'Reader';const joinedDate=profile?.created_at?new Date(profile.created_at).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'Recently';
  if(route!=='profile'||!user)return null;
  return <main className="profile-v2-overlay"><div className="profile-v2-shell"><div className="profile-v2-top"><button type="button" onClick={()=>window.location.hash='home'} aria-label="Back">←</button></div><section className="profile-v2-card">
    <div className="profile-v2-header"><div className="profile-v2-avatar-wrap"><img src={avatar||AVATARS[0]} alt="Profile avatar"/>{editing&&<button type="button" className="profile-v2-pencil" onClick={()=>setAvatarPicker(v=>!v)}>✎</button>}{editing&&avatarPicker&&<div className="profile-v2-avatar-picker"><div className="profile-v2-picker-title"><strong>Choose your profile picture</strong><button type="button" onClick={()=>setAvatarPicker(false)}>×</button></div><div className="profile-v2-avatar-grid">{AVATARS.map(src=><button type="button" key={src} className={avatar===src?'selected':''} onClick={()=>{setAvatar(src);setAvatarPicker(false)}}><img src={src} alt=""/></button>)}</div></div>}</div><div className="profile-v2-heading"><p className="section-eyebrow">PROFILE</p><h1>{display}</h1><p>@{profile?.username||'set-your-username'}</p><small>Joined {joinedDate}</small></div>{!editing&&<button type="button" className="profile-v2-edit-button" onClick={()=>{setError('');setMessage('');setEditing(true)}}>Edit Profile</button>}</div>
    {editing?<form className="profile-v2-edit-form" onSubmit={save}><label>Display name<input value={displayName} onChange={e=>setDisplayName(e.target.value)} maxLength={60} required/></label><label>Username<input value={username} onChange={e=>setUsername(e.target.value)} placeholder="your_handle" maxLength={24}/></label><label>Email / Gmail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/></label><label>Bio<textarea value={bio} onChange={e=>setBio(e.target.value)} placeholder="Tell readers a little about yourself" maxLength={240} rows="3"/></label><div className="profile-v2-edit-actions"><button type="button" onClick={()=>{setEditing(false);setAvatarPicker(false);load(user)}}>Cancel</button><button className="primary-button" type="submit" disabled={saving}>{saving?'Saving…':'Save Changes'}</button></div>{error&&<p className="profile-v2-error">{error}</p>}{message&&<p className="profile-v2-message">{message}</p>}</form>:<div className="profile-v2-bio">{profile?.bio?<p>{profile.bio}</p>:<p className="muted">Add a short bio so your profile feels like yours.</p>}</div>}
    {!editing&&<><div className="profile-v2-stats"><div><strong>{chaptersRead}</strong><span>Chapters read</span></div><div><strong>{bookmarks.length}</strong><span>Favourites</span></div><div><strong>{ratings.length}</strong><span>Ratings</span></div></div><div className="profile-v2-tabs">{[['history','Last Read'],['bookmarks','Favourites'],['ratings','My Ratings'],['comments','My Comments']].map(([id,label])=><button type="button" key={id} className={tab===id?'active':''} onClick={()=>{setTab(id);localStorage.setItem('atma-profile-tab',id)}}>{label}</button>)}</div><div className="profile-v2-list">{!list.length?<div className="profile-v2-empty"><h3>{tab==='history'?'Nothing read yet':tab==='bookmarks'?'No favourites yet':tab==='ratings'?'No ratings yet':'No comments yet'}</h3><p>{tab==='comments'?'Share your thoughts while reading and they will appear here.':tab==='history'?'Your latest reading position will appear here.':'Start reading Atma Rekha and your activity will appear here.'}</p></div>:list.map(row=>{const chapter=row.chapters;return tab==='comments'?<button type="button" key={row.id} className="profile-v2-comment-item" onClick={()=>row.chapter_id&&(window.location.hash=`read-chapter/${encodeURIComponent(row.chapter_id)}`)}><div><strong>{row.content}</strong><small>{relativeTime(row.created_at)}</small></div><b>Open →</b></button>:!chapter?null:<button type="button" key={row.id||row.chapter_id} className="profile-v2-list-item" onClick={()=>window.location.hash=`read-chapter/${encodeURIComponent(chapter.id)}`}><div>{chapter.cover_url?<img src={chapter.cover_url} alt=""/>:<span>AR</span>}<div><small>CHAPTER {chapter.chapter_number}</small><strong>{chapter.title}</strong></div></div><b>{tab==='ratings'?`${row.rating}/10 ★`:tab==='history'?`Page ${row.page_number||1} →`:'Read →'}</b></button>})}</div><div style={{display:'grid',gap:10}}><button type="button" className="profile-community-card" onClick={()=>window.location.hash='community'}><span className="profile-community-icon">🤝</span><span><strong>Community</strong><small>Creator updates and messages</small></span><b>→</b></button><button type="button" className="profile-community-card" onClick={()=>{setMemberContent(true);setMemberSection(null)}}><span className="profile-community-icon">🌸</span><span><strong>Member Content</strong><small>Exclusive Atma Rekha content</small></span><b>→</b></button></div><button type="button" className="profile-signout" onClick={signOut}>Sign out</button></>}
    {memberContent&&<div className="ec-backdrop" role="dialog" aria-modal="true"><div className="ec-sheet" style={{width:'min(760px,100%)',maxHeight:'92dvh',borderRadius:28,overflow:'auto'}}><header className="ec-header"><div><p className="ec-eyebrow">MEMBER CONTENT</p><h2>{memberSection?memberSection[1]:'Explore exclusive content'}</h2><p>{memberSection?'Explore this member section.':'Select a section to open its content.'}</p></div><button type="button" className="ec-close" onClick={()=>{setMemberContent(false);setMemberSection(null)}} aria-label="Close">×</button></header>{memberSection?<div style={{padding:'18px 16px 120px'}}><button type="button" className="profile-v2-modal-back" onClick={()=>setMemberSection(null)}>← All member content</button><div style={{marginTop:14,padding:22,border:'1px solid var(--legacy-303035-e6e1fdf4)',borderRadius:20,textAlign:'center'}}><div style={{fontSize:32}}>🌸</div><h3 style={{margin:'10px 0 6px'}}>{memberSection[1]}</h3><p style={{margin:0,color:'var(--legacy-92929b-335f3b85)',lineHeight:1.55}}>{memberSection[2]}</p><div style={{marginTop:18,padding:16,borderRadius:14,background:'var(--legacy-17171a-3cf5c11b)',color:'var(--legacy-92929b-335f3b85)',fontSize:13}}>New {memberSection[1].toLowerCase()} will appear here as they are published.</div></div></div>:<div style={{display:'grid',gap:10,padding:'12px 16px 120px'}}>{MEMBER_CONTENT.map(item=><button type="button" key={item[0]} onClick={()=>setMemberSection(item)} style={{display:'grid',gridTemplateColumns:'42px minmax(0,1fr) auto',gap:12,alignItems:'center',textAlign:'left',padding:14,border:'1px solid var(--legacy-29292e-492ef570)',borderRadius:17,background:'var(--legacy-17171a-3cf5c11b)',color:'inherit'}}><span style={{width:42,height:42,display:'grid',placeItems:'center',borderRadius:13,background:'var(--legacy-23252c-6f764760)',fontSize:19}}>{item[0]==='characters'?'👤':item[0]==='power'?'⚡':item[0]==='qa'?'💬':item[0]==='diary'?'📓':item[0]==='sketches'?'✏️':item[0]==='rejected'?'🗂️':item[0]==='before-after'?'🖼️':item[0]==='weapons'?'⚔️':'🌸'}</span><span style={{minWidth:0}}><strong style={{display:'block',fontSize:14}}>{item[1]}</strong><small style={{display:'block',marginTop:4,color:'var(--legacy-92929b-335f3b85)',lineHeight:1.4}}>{item[2]}</small></span><b>→</b></button>)}</div>}</div></div>}
  </section></div></main>;
}
