import { useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import { supabase } from './supabase';

const profileRoute = route => route === 'profile' || route === 'bookmarks' || route === 'history';

function routeNow() { return window.location.hash.replace(/^#/, '') || 'home'; }
function avatarFor(user, profile) { return profile?.avatar_url || ''; }
function nameFor(user, profile) { return profile?.display_name || user?.user_metadata?.full_name || 'Reader'; }

function AuthPanel({ mode, setMode, onClose, onSignedIn }) {
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async event => {
    event.preventDefault(); if (busy) return; setBusy(true); setError(''); setMessage('');
    try {
      if (mode === 'signup') {
        if (!name.trim()) throw new Error('Please enter your name.');
        if (password.length < 6) throw new Error('Password must be at least 6 characters.');
        if (password !== confirmPassword) throw new Error('Passwords do not match.');
        const { data, error: authError } = await supabase.auth.signUp({ email: email.trim(), password, options: { data: { full_name: name.trim() } } });
        if (authError) throw authError;
        if (data.session) onSignedIn(); else setMessage('Check your email to verify your account, then sign in.');
      } else if (mode === 'login') {
        const { error: authError } = await supabase.auth.signInWithPassword({ email: email.trim(), password });
        if (authError) throw authError; onSignedIn();
      } else {
        const { error: authError } = await supabase.auth.resetPasswordForEmail(email.trim(), { redirectTo: `${window.location.origin}${window.location.pathname}#reset-password` });
        if (authError) throw authError; setMessage('Password reset instructions have been sent to your email.');
      }
    } catch (authError) { setError(authError?.message || 'Something went wrong. Please try again.'); } finally { setBusy(false); }
  };
  const title = mode === 'signup' ? 'Create your account' : mode === 'forgot' ? 'Reset your password' : 'Welcome back';
  return <div className="auth-panel-backdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) onClose(); }}><section className="auth-panel" role="dialog" aria-modal="true" aria-labelledby="auth-panel-title"><button type="button" className="auth-panel-close" onClick={onClose} aria-label="Close">×</button><p className="section-eyebrow">ATMA REKHA</p><h2 id="auth-panel-title">{title}</h2><p className="auth-panel-subtitle">{mode === 'signup' ? 'Create your reader account.' : mode === 'forgot' ? 'Enter your email and we’ll send you a secure reset link.' : 'Sign in to continue reading and access your profile.'}</p><form onSubmit={submit} className="auth-panel-form">{mode === 'signup' && <label>Name<input value={name} onChange={event => setName(event.target.value)} autoComplete="name" required /></label>}<label>Email<input type="email" value={email} onChange={event => setEmail(event.target.value)} autoComplete="email" required /></label>{mode !== 'forgot' && <label>Password<input type="password" value={password} onChange={event => setPassword(event.target.value)} autoComplete={mode === 'signup' ? 'new-password' : 'current-password'} required /></label>}{mode === 'signup' && <label>Confirm password<input type="password" value={confirmPassword} onChange={event => setConfirmPassword(event.target.value)} autoComplete="new-password" required /></label>}<button type="submit" className="primary-button" disabled={busy}>{busy ? 'Please wait…' : mode === 'signup' ? 'Create account' : mode === 'forgot' ? 'Send reset link' : 'Sign in'}</button></form>{error && <p className="auth-panel-error" role="alert">{error}</p>}{message && <p className="auth-panel-message" role="status">{message}</p>}{mode === 'login' && <button className="auth-panel-link" onClick={() => { setMode('forgot'); setError(''); setMessage(''); }}>Forgot password?</button>}{mode === 'forgot' && <button className="auth-panel-link" onClick={() => { setMode('login'); setError(''); setMessage(''); }}>Back to sign in</button>}{mode !== 'forgot' && <p className="auth-panel-switch">{mode === 'login' ? 'New to Atma Rekha?' : 'Already have an account?'} <button onClick={() => { setMode(mode === 'login' ? 'signup' : 'login'); setError(''); setMessage(''); }}>{mode === 'login' ? 'Create account' : 'Sign in'}</button></p>}</section></div>;
}

function ResetPasswordPanel({ onClose }) {
  const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async event => { event.preventDefault(); if (password.length < 6) { setError('Password must be at least 6 characters.'); return; } if (password !== confirm) { setError('Passwords do not match.'); return; } setBusy(true); setError(''); const { error: updateError } = await supabase.auth.updateUser({ password }); setBusy(false); if (updateError) setError(updateError.message); else setMessage('Password updated successfully.'); };
  return <div className="auth-panel-backdrop"><section className="auth-panel" role="dialog" aria-modal="true"><button type="button" className="auth-panel-close" onClick={onClose} aria-label="Close">×</button><p className="section-eyebrow">ATMA REKHA</p><h2>Choose a new password</h2><form onSubmit={submit} className="auth-panel-form"><label>New password<input type="password" value={password} onChange={event => setPassword(event.target.value)} required /></label><label>Confirm password<input type="password" value={confirm} onChange={event => setConfirm(event.target.value)} required /></label><button className="primary-button" disabled={busy}>{busy ? 'Updating…' : 'Update password'}</button></form>{error && <p className="auth-panel-error">{error}</p>}{message && <p className="auth-panel-message">{message}</p>}</section></div>;
}

function UserMenu({ user, profile, onSignOut }) {
  const [open, setOpen] = useState(false); const avatar = avatarFor(user, profile); const name = nameFor(user, profile);
  return <div className="user-auth-menu"><button type="button" className="user-auth-avatar-button" onClick={() => setOpen(value => !value)} aria-expanded={open} aria-label="Open account menu">{avatar ? <img src={avatar} alt="" className="user-auth-avatar"/> : <span className="user-auth-avatar-fallback">{name.slice(0, 1).toUpperCase()}</span>}<span className="user-auth-name">{name}</span><span className="user-auth-chevron">⌄</span></button>{open && <div className="user-auth-dropdown"><div className="user-auth-dropdown-head"><strong>{name}</strong><span>{user.email}</span></div><button onClick={() => { window.location.hash = 'profile'; setOpen(false); }}>Profile</button><button onClick={() => { window.location.hash = 'bookmarks'; setOpen(false); }}>Bookmarks</button><button onClick={() => { window.location.hash = 'history'; setOpen(false); }}>History</button><button className="user-auth-signout" onClick={async () => { setOpen(false); await onSignOut(); }}>Sign out</button></div>}</div>;
}

function ContinueReading({ rows, onOpen }) {
  if (!rows.length) return null; return <section className="home-continue-section"><div className="home-continue-heading"><div><p className="section-eyebrow">YOUR READING</p><h2>Continue Reading</h2></div><button type="button" onClick={() => { window.location.hash = 'history'; }}>History →</button></div><div className="home-continue-row">{rows.slice(0, 3).map(row => { const chapter = row.chapters; const progress = Number(row.page_number || 1); if (!chapter) return null; return <button type="button" className="home-continue-card" key={row.chapter_id} onClick={() => onOpen(chapter.id)}>{chapter.cover_url ? <img src={chapter.cover_url} alt=""/> : <div className="home-continue-placeholder">AR</div>}<div><span>CHAPTER {chapter.chapter_number}</span><h3>{chapter.title}</h3><p>Resume from page {progress}</p></div><b>→</b></button>; })}</div></section>;
}

function ProfilePage({ user, profile, setProfile, activeTab, setActiveTab }) {
  const [username, setUsername] = useState(profile?.username || ''); const [displayName, setDisplayName] = useState(profile?.display_name || ''); const [bio, setBio] = useState(profile?.bio || ''); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); const [rows, setRows] = useState([]); const [bookmarks, setBookmarks] = useState([]); const [ratings, setRatings] = useState([]); const [loading, setLoading] = useState(false); const avatar = avatarFor(user, profile); const display = nameFor(user, profile);
  useEffect(() => { setUsername(profile?.username || ''); setDisplayName(profile?.display_name || ''); setBio(profile?.bio || ''); }, [profile]);
  useEffect(() => { let cancelled = false; const load = async () => { setLoading(true); const [historyResult, bookmarkResult, ratingResult] = await Promise.all([supabase.from('reading_history').select('chapter_id,page_number,updated_at,chapters(id,chapter_number,title,cover_url,status)').eq('user_id', user.id).order('updated_at', { ascending: false }).limit(50), supabase.from('bookmarks').select('id,chapter_id,created_at,chapters(id,chapter_number,title,cover_url,status)').eq('user_id', user.id).order('created_at', { ascending: false }).limit(50), supabase.from('chapter_ratings').select('id,chapter_id,rating,created_at,chapters(id,chapter_number,title,cover_url,status)').eq('user_id', user.id).order('created_at', { ascending: false }).limit(50)]); if (!cancelled) { setRows(historyResult.data || []); setBookmarks(bookmarkResult.data || []); setRatings(ratingResult.data || []); setLoading(false); } }; load(); return () => { cancelled = true; }; }, [user.id, activeTab]);
  const save = async event => { event.preventDefault(); if (saving) return; setSaving(true); setMessage(''); const cleanUsername = username.trim().toLowerCase().replace(/[^a-z0-9_]/g, '').slice(0, 24); const updates = { username: cleanUsername || null, display_name: displayName.trim().slice(0, 60) || display, bio: bio.trim().slice(0, 240) || null, updated_at: new Date().toISOString() }; const { data, error } = await supabase.from('profiles').update(updates).eq('id', user.id).select().single(); if (error) setMessage(error.code === '23505' ? 'That username is already taken.' : error.message); else { setProfile(data); setMessage('Profile saved.'); } setSaving(false); };
  const list = activeTab === 'history' ? rows : activeTab === 'bookmarks' ? bookmarks : ratings; const stats = { history: rows.length, bookmarks: bookmarks.length, ratings: ratings.length };
  return <main className="user-profile-page"><div className="user-profile-top"><button className="user-profile-back" onClick={() => { window.location.hash = 'home'; }}>←</button><span>ATMA REKHA</span></div><section className="user-profile-card"><div className="user-profile-identity">{avatar ? <img src={avatar} alt=""/> : <div className="user-profile-avatar-fallback">{display.slice(0, 1).toUpperCase()}</div>}<div><p className="section-eyebrow">READER PROFILE</p><h1>{display}</h1><p>@{profile?.username || 'set-your-username'}</p><small>Joined {profile?.created_at ? new Date(profile.created_at).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) : 'recently'}</small></div></div><form className="user-profile-form" onSubmit={save}><label>Display name<input value={displayName} onChange={event => setDisplayName(event.target.value)}/></label><label>Username<input value={username} onChange={event => setUsername(event.target.value)} placeholder="your_handle" maxLength={24}/></label><label>Bio<textarea value={bio} onChange={event => setBio(event.target.value)} placeholder="A short bio (optional)" maxLength={240} rows="3"/></label><button className="primary-button" disabled={saving}>{saving ? 'Saving…' : 'Save profile'}</button>{message && <p className="user-profile-message">{message}</p>}</form><div className="user-profile-stats"><div><strong>{stats.history}</strong><span>Chapters read</span></div><div><strong>{stats.bookmarks}</strong><span>Saved chapters</span></div><div><strong>{stats.ratings}</strong><span>Ratings given</span></div></div><div className="user-profile-tabs">{[['history','History'],['bookmarks','Bookmarks'],['ratings','My Ratings']].map(([id,label]) => <button key={id} className={activeTab === id ? 'active' : ''} onClick={() => setActiveTab(id)}>{label}</button>)}</div><div className="user-profile-list">{loading ? <div className="loading-state"><span className="loading-spinner"/><p>Loading…</p></div> : !list.length ? <div className="empty-state"><h3>{activeTab === 'history' ? 'No reading history yet' : activeTab === 'bookmarks' ? 'No bookmarks yet' : 'No ratings yet'}</h3><p>Start reading Atma Rekha and your activity will appear here.</p></div> : list.map(row => { const chapter = row.chapters; if (!chapter) return null; return <button key={row.id || row.chapter_id} className="user-profile-list-item" onClick={() => { window.location.hash = `read-chapter/${encodeURIComponent(chapter.id)}`; }}><div>{chapter.cover_url ? <img src={chapter.cover_url} alt=""/> : <span>AR</span>}<div><small>CHAPTER {chapter.chapter_number}</small><strong>{chapter.title}</strong></div></div><b>{activeTab === 'ratings' ? `${row.rating}/10 ★` : activeTab === 'history' ? `Page ${row.page_number || 1} →` : 'Read →'}</b></button>; })}</div></section></main>;
}

export default function UserAuth() {
  const [route, setRoute] = useState(routeNow); const [session, setSession] = useState(null); const [profile, setProfile] = useState(null); const [continueRows, setContinueRows] = useState([]); const [profileTab, setProfileTab] = useState('history'); const [authMode, setAuthMode] = useState(null); const [resetMode, setResetMode] = useState(false);
  useEffect(() => { const onHash = () => setRoute(routeNow()); window.addEventListener('hashchange', onHash); return () => window.removeEventListener('hashchange', onHash); }, []);
  const loadUserData = async currentUser => { if (!currentUser) { setProfile(null); setContinueRows([]); return; } const { data: profileRow } = await supabase.from('profiles').select('*').eq('id', currentUser.id).maybeSingle(); setProfile(profileRow || null); const { data: history } = await supabase.from('reading_history').select('chapter_id,page_number,updated_at,chapters(id,chapter_number,title,cover_url,status)').eq('user_id', currentUser.id).order('updated_at', { ascending: false }).limit(3); setContinueRows(history || []); };
  useEffect(() => { let alive = true; supabase.auth.getSession().then(({ data }) => { if (alive) { setSession(data?.session || null); if (data?.session?.user) loadUserData(data.session.user); } }); const { data: listener } = supabase.auth.onAuthStateChange((_event, nextSession) => { if (!alive) return; setSession(nextSession); if (nextSession?.user) loadUserData(nextSession.user); else { setProfile(null); setContinueRows([]); } }); return () => { alive = false; listener.subscription.unsubscribe(); }; }, []);
  const user = session?.user || null;
  const signOut = async () => { await supabase.auth.signOut(); window.location.hash = 'home'; };
  useEffect(() => { if (!user) return; const match = route.match(/^read-chapter\/(.+)$/); if (!match) return; const chapterId = decodeURIComponent(match[1]); supabase.from('reading_history').upsert({ user_id: user.id, chapter_id: chapterId, page_number: 1, updated_at: new Date().toISOString() }, { onConflict: 'user_id,chapter_id' }).then(({ error: historyError }) => { if (historyError) console.warn('Reading history:', historyError.message); else loadUserData(user); }); }, [route, user?.id]);
  const authControl = user ? <UserMenu user={user} profile={profile} onSignOut={signOut}/> : <button type="button" className="email-signin-button" onClick={() => setAuthMode('login')}>Sign in</button>;
  const profilePortal = user && profileRoute(route) ? createPortal(<ProfilePage user={user} profile={profile || {}} setProfile={setProfile} activeTab={profileTab} setActiveTab={setProfileTab}/>, document.body) : null;
  const homePortal = route === 'home' && user && continueRows.length ? createPortal(<ContinueReading rows={continueRows} onOpen={chapterId => { window.location.hash = `read-chapter/${encodeURIComponent(chapterId)}`; }}/>, document.querySelector('.home-page') || document.body) : null;
  const authPortal = authMode ? createPortal(<AuthPanel mode={authMode} setMode={setAuthMode} onClose={() => setAuthMode(null)} onSignedIn={() => setAuthMode(null)}/>, document.body) : null;
  const resetPortal = resetMode ? createPortal(<ResetPasswordPanel onClose={() => { setResetMode(false); window.location.hash = 'home'; }}/>, document.body) : null;
  useEffect(() => { if (route === 'reset-password') setResetMode(true); }, [route]);
  return <>{createPortal(<div className="user-auth-fixed">{authControl}</div>, document.body)}{profilePortal}{homePortal}{authPortal}{resetPortal}</>;
}
