import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const ALLOWED_ORIGINS = new Set(["https://www.atmarekha.in", "https://atmarekha.in", "http://localhost:5173"]);
const VERSION = Deno.env.get("CASHFREE_API_VERSION") || "2025-01-01";
const ENV = (Deno.env.get("CASHFREE_ENVIRONMENT") || "sandbox").toLowerCase();
const BASE = ENV === "production" ? "https://api.cashfree.com/pg" : "https://sandbox.cashfree.com/pg";
function cors(o:string|null){return {"Access-Control-Allow-Origin":o&&ALLOWED_ORIGINS.has(o)?o:"https://www.atmarekha.in","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS",Vary:"Origin"};}
function json(b:Record<string,unknown>,s:number,o:string|null){return new Response(JSON.stringify(b),{status:s,headers:{...cors(o),"Content-Type":"application/json"}});}
function mapStatus(s:string){if(s==="ACTIVE")return"active";if(["ON_HOLD","PAUSED"].includes(s))return"paused";if(["CANCELLED","CUSTOMER_CANCELLED"].includes(s))return"cancelled";if(["COMPLETED","EXPIRED","LINK_EXPIRED","CARD_EXPIRED"].includes(s))return"expired";if(s==="FAILED")return"failed";return"pending";}
function periodEnd(d:any){const n=d?.next_schedule_date;if(n)return new Date(n).toISOString();const first=d?.subscription_first_charge_time||d?.authorization_details?.authorization_time||d?.authorisation_details?.authorization_time;if(first){const x=new Date(first);if(!Number.isNaN(x.getTime())){x.setMonth(x.getMonth()+1);return x.toISOString();}}return null;}
Deno.serve(async req=>{const o=req.headers.get("origin");if(req.method==="OPTIONS")return new Response("ok",{headers:cors(o)});if(req.method!=="POST")return json({error:"Method not allowed."},405,o);try{const url=Deno.env.get("SUPABASE_URL")||"",anon=Deno.env.get("SUPABASE_ANON_KEY")||"",service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";if(!url||!anon||!service)return json({error:"Supabase server configuration is incomplete."},500,o);const ah=req.headers.get("Authorization");if(!ah)return json({error:"Authentication required."},401,o);const auth=createClient(url,anon,{global:{headers:{Authorization:ah}}});const {data:{user},error:ae}=await auth.auth.getUser();if(ae||!user)return json({error:"Authentication failed."},401,o);const admin=createClient(url,service);const body=await req.json().catch(()=>({}));const id=String(body?.subscription_id||"");if(!id)return json({error:"Subscription ID is required."},400,o);const {data:local}=await admin.from("user_subscriptions").select("id,user_id,status,current_period_end,cancel_at_period_end,provider_subscription_id").eq("user_id",user.id).eq("provider","cashfree").eq("provider_subscription_id",id).maybeSingle();if(!local)return json({error:"Subscription does not belong to this account."},403,o);const r=await fetch(`${BASE}/subscriptions/${encodeURIComponent(id)}`,{headers:{accept:"application/json","x-api-version":VERSION,"x-client-id":Deno.env.get("CASHFREE_CLIENT_ID")||"","x-client-secret":Deno.env.get("CASHFREE_CLIENT_SECRET")||""}});const remote=await r.json().catch(()=>null);if(!r.ok)return json({error:remote?.message||`Cashfree returned HTTP ${r.status}.`},502,o);const status=mapStatus(String(remote?.subscription_status||""));let end=periodEnd(remote);if(status==="active"&&!end&&local.current_period_end&&new Date(local.current_period_end).getTime()>Date.now())end=local.current_period_end;if(status==="active"&&!end)end=new Date(Date.now()+31*86400000).toISOString();const {error:ue}=await admin.from("user_subscriptions").update({status,current_period_start:status==="active"?new Date().toISOString():undefined,current_period_end:end,updated_at:new Date().toISOString()}).eq("id",local.id);if(ue)return json({error:`Could not update membership: ${ue.message}`},500,o);return json({success:status==="active",status,current_period_end:end,subscription_id:id},200,o);}catch(e){console.error("Cashfree subscription verification failed:",e);return json({error:e instanceof Error?e.message:"Unable to verify membership."},500,o);}});
